// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pos/poc/v1/contribution.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Endorsement represents a validator's endorsement of a contribution
type Endorsement struct {
	// val_addr is the validator operator address (bech32)
	ValAddr string `protobuf:"bytes,1,opt,name=val_addr,json=valAddr,proto3" json:"val_addr,omitempty"`
	// decision is true for approval, false for rejection
	Decision bool `protobuf:"varint,2,opt,name=decision,proto3" json:"decision,omitempty"`
	// power is the validator's consensus power at time of endorsement
	Power cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=power,proto3,customtype=cosmossdk.io/math.Int" json:"power"`
	// time is the unix timestamp of the endorsement
	Time int64 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (m *Endorsement) Reset()         { *m = Endorsement{} }
func (m *Endorsement) String() string { return proto.CompactTextString(m) }
func (*Endorsement) ProtoMessage()    {}
func (*Endorsement) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ca796103186b6f, []int{0}
}
func (m *Endorsement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Endorsement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Endorsement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Endorsement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endorsement.Merge(m, src)
}
func (m *Endorsement) XXX_Size() int {
	return m.Size()
}
func (m *Endorsement) XXX_DiscardUnknown() {
	xxx_messageInfo_Endorsement.DiscardUnknown(m)
}

var xxx_messageInfo_Endorsement proto.InternalMessageInfo

func (m *Endorsement) GetValAddr() string {
	if m != nil {
		return m.ValAddr
	}
	return ""
}

func (m *Endorsement) GetDecision() bool {
	if m != nil {
		return m.Decision
	}
	return false
}

func (m *Endorsement) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// Contribution represents a proof-of-contribution submission
type Contribution struct {
	// id is the unique identifier for this contribution
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// contributor is the address that submitted the contribution
	Contributor string `protobuf:"bytes,2,opt,name=contributor,proto3" json:"contributor,omitempty"`
	// ctype is the contribution type (e.g., "code", "record", "relay", "green")
	Ctype string `protobuf:"bytes,3,opt,name=ctype,proto3" json:"ctype,omitempty"`
	// uri is a pointer to evidence (IPFS/Git/etc.)
	Uri string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	// hash is the content hash or merkle root
	Hash []byte `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	// endorsements is the list of validator endorsements
	Endorsements []Endorsement `protobuf:"bytes,6,rep,name=endorsements,proto3" json:"endorsements"`
	// verified indicates if the contribution has reached quorum
	Verified bool `protobuf:"varint,7,opt,name=verified,proto3" json:"verified,omitempty"`
	// block_height is the height at which this contribution was submitted
	BlockHeight int64 `protobuf:"varint,8,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// block_time is the unix timestamp when this contribution was submitted
	BlockTime int64 `protobuf:"varint,9,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	// rewarded indicates if the contribution has been rewarded
	Rewarded bool `protobuf:"varint,10,opt,name=rewarded,proto3" json:"rewarded,omitempty"`
}

func (m *Contribution) Reset()         { *m = Contribution{} }
func (m *Contribution) String() string { return proto.CompactTextString(m) }
func (*Contribution) ProtoMessage()    {}
func (*Contribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ca796103186b6f, []int{1}
}
func (m *Contribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Contribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Contribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contribution.Merge(m, src)
}
func (m *Contribution) XXX_Size() int {
	return m.Size()
}
func (m *Contribution) XXX_DiscardUnknown() {
	xxx_messageInfo_Contribution.DiscardUnknown(m)
}

var xxx_messageInfo_Contribution proto.InternalMessageInfo

func (m *Contribution) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contribution) GetContributor() string {
	if m != nil {
		return m.Contributor
	}
	return ""
}

func (m *Contribution) GetCtype() string {
	if m != nil {
		return m.Ctype
	}
	return ""
}

func (m *Contribution) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Contribution) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Contribution) GetEndorsements() []Endorsement {
	if m != nil {
		return m.Endorsements
	}
	return nil
}

func (m *Contribution) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *Contribution) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *Contribution) GetBlockTime() int64 {
	if m != nil {
		return m.BlockTime
	}
	return 0
}

func (m *Contribution) GetRewarded() bool {
	if m != nil {
		return m.Rewarded
	}
	return false
}

// Credits represents accumulated PoC credits for an address
type Credits struct {
	// address is the contributor's address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// amount is the accumulated credit units
	Amount cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *Credits) Reset()         { *m = Credits{} }
func (m *Credits) String() string { return proto.CompactTextString(m) }
func (*Credits) ProtoMessage()    {}
func (*Credits) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ca796103186b6f, []int{2}
}
func (m *Credits) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Credits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Credits.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Credits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credits.Merge(m, src)
}
func (m *Credits) XXX_Size() int {
	return m.Size()
}
func (m *Credits) XXX_DiscardUnknown() {
	xxx_messageInfo_Credits.DiscardUnknown(m)
}

var xxx_messageInfo_Credits proto.InternalMessageInfo

func (m *Credits) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Endorsement)(nil), "pos.poc.v1.Endorsement")
	proto.RegisterType((*Contribution)(nil), "pos.poc.v1.Contribution")
	proto.RegisterType((*Credits)(nil), "pos.poc.v1.Credits")
}

func init() { proto.RegisterFile("pos/poc/v1/contribution.proto", fileDescriptor_18ca796103186b6f) }

var fileDescriptor_18ca796103186b6f = []byte{
	// 492 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x6f, 0xd3, 0x3e,
	0x18, 0xc7, 0x9b, 0xfe, 0xef, 0xd3, 0xea, 0xf7, 0x03, 0xab, 0x08, 0x53, 0x69, 0x59, 0xe9, 0xa9,
	0x08, 0x2d, 0xd1, 0xb6, 0x1b, 0xb7, 0xb6, 0x42, 0x62, 0xd7, 0xc0, 0x89, 0x4b, 0x95, 0xc6, 0xa6,
	0xb5, 0xd6, 0xf8, 0x89, 0x6c, 0x37, 0x83, 0x2b, 0xaf, 0x80, 0x17, 0x33, 0xde, 0xc3, 0x8e, 0xd3,
	0xb8, 0x20, 0x0e, 0x13, 0x6a, 0xdf, 0x08, 0x8a, 0x9d, 0x6d, 0xe5, 0x02, 0xe2, 0x12, 0x3d, 0xff,
	0xf3, 0xf5, 0xe7, 0xb1, 0xe1, 0x20, 0x43, 0x1d, 0x66, 0x98, 0x84, 0xf9, 0x71, 0x98, 0xa0, 0x34,
	0x4a, 0x2c, 0x36, 0x46, 0xa0, 0x0c, 0x32, 0x85, 0x06, 0x09, 0x64, 0xa8, 0x83, 0x0c, 0x93, 0x20,
	0x3f, 0x1e, 0x3c, 0x8e, 0x53, 0x21, 0x31, 0xb4, 0x5f, 0x97, 0x1e, 0xf4, 0x97, 0xb8, 0x44, 0x6b,
	0x86, 0x85, 0x55, 0x46, 0x9f, 0x25, 0xa8, 0x53, 0xd4, 0x73, 0x97, 0x70, 0x8e, 0x4b, 0x8d, 0xbe,
	0x7a, 0xd0, 0x7d, 0x2d, 0x19, 0x2a, 0xcd, 0x53, 0x2e, 0x0d, 0x39, 0x85, 0x76, 0x1e, 0xaf, 0xe7,
	0x31, 0x63, 0x8a, 0x7a, 0x43, 0x6f, 0xdc, 0x99, 0xd2, 0x9b, 0xcb, 0xa3, 0x7e, 0xd9, 0x33, 0x61,
	0x4c, 0x71, 0xad, 0xdf, 0x1a, 0x25, 0xe4, 0x32, 0x6a, 0xe5, 0xf1, 0xba, 0x88, 0x90, 0x01, 0xb4,
	0x19, 0x4f, 0x84, 0x16, 0x28, 0x69, 0x75, 0xe8, 0x8d, 0xdb, 0xd1, 0xbd, 0x4f, 0x26, 0xd0, 0xc8,
	0xf0, 0x82, 0x2b, 0x5a, 0xb3, 0xd3, 0x5e, 0x5e, 0xdd, 0x1e, 0x56, 0x7e, 0xdc, 0x1e, 0x3e, 0x71,
	0x13, 0x35, 0x3b, 0x0f, 0x04, 0x86, 0x69, 0x6c, 0x56, 0xc1, 0x99, 0x34, 0x37, 0x97, 0x47, 0x50,
	0xfe, 0xea, 0x4c, 0x9a, 0xc8, 0x75, 0x12, 0x02, 0x75, 0x23, 0x52, 0x4e, 0xeb, 0x43, 0x6f, 0x5c,
	0x8b, 0xac, 0x3d, 0xfa, 0x56, 0x85, 0xde, 0x6c, 0x0f, 0x0f, 0xf9, 0x0f, 0xaa, 0x82, 0x59, 0xc9,
	0xf5, 0xa8, 0x2a, 0x18, 0x79, 0x05, 0xdd, 0x7b, 0x7c, 0xa8, 0xac, 0xac, 0x3f, 0x9d, 0x65, 0xbf,
	0x98, 0xf4, 0xa1, 0x91, 0x98, 0x4f, 0x19, 0x77, 0x9a, 0x23, 0xe7, 0x90, 0x47, 0x50, 0xdb, 0x28,
	0x61, 0x55, 0x74, 0xa2, 0xc2, 0x2c, 0x84, 0xad, 0x62, 0xbd, 0xa2, 0x8d, 0xa1, 0x37, 0xee, 0x45,
	0xd6, 0x26, 0x13, 0xe8, 0xf1, 0x07, 0x9e, 0x9a, 0x36, 0x87, 0xb5, 0x71, 0xf7, 0xe4, 0x69, 0xf0,
	0xb0, 0xb7, 0x60, 0x8f, 0xf7, 0xb4, 0x5e, 0xf0, 0x88, 0x7e, 0x6b, 0x29, 0x70, 0xe6, 0x5c, 0x89,
	0x0f, 0x82, 0x33, 0xda, 0x72, 0x38, 0xef, 0x7c, 0xf2, 0x1c, 0x7a, 0x8b, 0x35, 0x26, 0xe7, 0xf3,
	0x15, 0x17, 0xcb, 0x95, 0xa1, 0x6d, 0xcb, 0xa4, 0x6b, 0x63, 0x6f, 0x6c, 0x88, 0x1c, 0x00, 0xb8,
	0x12, 0x0b, 0xad, 0x63, 0x0b, 0x3a, 0x36, 0xf2, 0x4e, 0xa4, 0xbc, 0x98, 0xae, 0xf8, 0x45, 0xac,
	0x18, 0x67, 0x14, 0xdc, 0xf4, 0x3b, 0x7f, 0xf4, 0xd9, 0x83, 0xd6, 0x4c, 0x71, 0x26, 0x8c, 0x26,
	0x27, 0xd0, 0x8a, 0x1d, 0xa2, 0xbf, 0x5f, 0x84, 0xb2, 0x90, 0xcc, 0xa0, 0x19, 0xa7, 0xb8, 0x91,
	0xa6, 0xe4, 0xfd, 0x4f, 0xdb, 0x2e, 0x5b, 0xa7, 0x2f, 0xae, 0xb6, 0xbe, 0x77, 0xbd, 0xf5, 0xbd,
	0x9f, 0x5b, 0xdf, 0xfb, 0xb2, 0xf3, 0x2b, 0xd7, 0x3b, 0xbf, 0xf2, 0x7d, 0xe7, 0x57, 0xde, 0xff,
	0x5f, 0xbc, 0x8d, 0x8f, 0xf6, 0x75, 0x14, 0x1b, 0xd1, 0x8b, 0xa6, 0xbd, 0xc4, 0xa7, 0xbf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x22, 0x4f, 0x66, 0xf6, 0x35, 0x03, 0x00, 0x00,
}

func (m *Endorsement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Endorsement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Endorsement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Time != 0 {
		i = encodeVarintContribution(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.Power.Size()
		i -= size
		if _, err := m.Power.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintContribution(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Decision {
		i--
		if m.Decision {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.ValAddr) > 0 {
		i -= len(m.ValAddr)
		copy(dAtA[i:], m.ValAddr)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.ValAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Contribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Rewarded {
		i--
		if m.Rewarded {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.BlockTime != 0 {
		i = encodeVarintContribution(dAtA, i, uint64(m.BlockTime))
		i--
		dAtA[i] = 0x48
	}
	if m.BlockHeight != 0 {
		i = encodeVarintContribution(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.Verified {
		i--
		if m.Verified {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.Endorsements) > 0 {
		for iNdEx := len(m.Endorsements) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Endorsements[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintContribution(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Uri) > 0 {
		i -= len(m.Uri)
		copy(dAtA[i:], m.Uri)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.Uri)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Ctype) > 0 {
		i -= len(m.Ctype)
		copy(dAtA[i:], m.Ctype)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.Ctype)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Contributor) > 0 {
		i -= len(m.Contributor)
		copy(dAtA[i:], m.Contributor)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.Contributor)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintContribution(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Credits) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Credits) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Credits) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintContribution(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintContribution(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintContribution(dAtA []byte, offset int, v uint64) int {
	offset -= sovContribution(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Endorsement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValAddr)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	if m.Decision {
		n += 2
	}
	l = m.Power.Size()
	n += 1 + l + sovContribution(uint64(l))
	if m.Time != 0 {
		n += 1 + sovContribution(uint64(m.Time))
	}
	return n
}

func (m *Contribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovContribution(uint64(m.Id))
	}
	l = len(m.Contributor)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.Ctype)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.Uri)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	if len(m.Endorsements) > 0 {
		for _, e := range m.Endorsements {
			l = e.Size()
			n += 1 + l + sovContribution(uint64(l))
		}
	}
	if m.Verified {
		n += 2
	}
	if m.BlockHeight != 0 {
		n += 1 + sovContribution(uint64(m.BlockHeight))
	}
	if m.BlockTime != 0 {
		n += 1 + sovContribution(uint64(m.BlockTime))
	}
	if m.Rewarded {
		n += 2
	}
	return n
}

func (m *Credits) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovContribution(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovContribution(uint64(l))
	return n
}

func sovContribution(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozContribution(x uint64) (n int) {
	return sovContribution(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Endorsement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContribution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Endorsement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Endorsement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decision", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Decision = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Power.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipContribution(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContribution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Contribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContribution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contributor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contributor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ctype", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ctype = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Endorsements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Endorsements = append(m.Endorsements, Endorsement{})
			if err := m.Endorsements[len(m.Endorsements)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Verified = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockTime", wireType)
			}
			m.BlockTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewarded", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Rewarded = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipContribution(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContribution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Credits) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContribution
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Credits: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Credits: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContribution
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContribution
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContribution(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContribution
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContribution(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContribution
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContribution
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthContribution
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupContribution
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthContribution
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthContribution        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContribution          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupContribution = fmt.Errorf("proto: unexpected end of group")
)
