// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pos/poc/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Tier represents a contribution tier based on accumulated credits
type Tier struct {
	Name   string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cutoff cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=cutoff,proto3,customtype=cosmossdk.io/math.Int" json:"cutoff"`
}

func (m *Tier) Reset()         { *m = Tier{} }
func (m *Tier) String() string { return proto.CompactTextString(m) }
func (*Tier) ProtoMessage()    {}
func (*Tier) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c909664d3187a, []int{0}
}
func (m *Tier) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Tier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Tier.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Tier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tier.Merge(m, src)
}
func (m *Tier) XXX_Size() int {
	return m.Size()
}
func (m *Tier) XXX_DiscardUnknown() {
	xxx_messageInfo_Tier.DiscardUnknown(m)
}

var xxx_messageInfo_Tier proto.InternalMessageInfo

func (m *Tier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Params defines the parameters for the poc module.
type Params struct {
	// quorum_pct is the percentage of voting power needed for verification (e.g., 0.67 for 2/3)
	QuorumPct cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=quorum_pct,json=quorumPct,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"quorum_pct"`
	// base_reward_unit is the base credits awarded per verified contribution
	BaseRewardUnit cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=base_reward_unit,json=baseRewardUnit,proto3,customtype=cosmossdk.io/math.Int" json:"base_reward_unit"`
	// inflation_share is the share of inflation routed to PoC pool (future use)
	InflationShare cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=inflation_share,json=inflationShare,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"inflation_share"`
	// max_per_block is the maximum submissions per block (rate limit)
	MaxPerBlock uint32 `protobuf:"varint,4,opt,name=max_per_block,json=maxPerBlock,proto3" json:"max_per_block,omitempty"`
	// tiers define contribution tiers based on accumulated credits
	Tiers []Tier `protobuf:"bytes,5,rep,name=tiers,proto3" json:"tiers"`
	// reward_denom is the denomination for withdrawing PoC rewards
	RewardDenom string `protobuf:"bytes,6,opt,name=reward_denom,json=rewardDenom,proto3" json:"reward_denom,omitempty"`
	// PERFORMANCE OPTIMIZATION: max_contributions_to_keep limits state growth
	// Only the most recent N verified contributions are kept
	// Older contributions are pruned during EndBlock
	// Default: 100000 (keeps ~100k contributions in state)
	MaxContributionsToKeep uint64 `protobuf:"varint,7,opt,name=max_contributions_to_keep,json=maxContributionsToKeep,proto3" json:"max_contributions_to_keep,omitempty"`
	// submission_fee is the fee required to submit a contribution
	// Default: 1000uomni (0.001 OMNI)
	SubmissionFee github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,8,opt,name=submission_fee,json=submissionFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"submission_fee"`
	// submission_burn_ratio is the percentage of submission_fee that gets burned
	// The remainder goes to the PoC reward pool
	// Default: 0.75 (75% burned, 25% to rewards)
	// DAO-governed range: 0.50 - 0.90
	SubmissionBurnRatio cosmossdk_io_math.LegacyDec `protobuf:"bytes,9,opt,name=submission_burn_ratio,json=submissionBurnRatio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"submission_burn_ratio"`
	// min_submission_fee is the minimum allowed submission fee (governance bound)
	// Prevents fee from being set too low
	MinSubmissionFee github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,10,opt,name=min_submission_fee,json=minSubmissionFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"min_submission_fee"`
	// max_submission_fee is the maximum allowed submission fee (governance bound)
	// Prevents fee from being set too high
	MaxSubmissionFee github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,11,opt,name=max_submission_fee,json=maxSubmissionFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"max_submission_fee"`
	// min_burn_ratio is the minimum allowed burn ratio (governance bound)
	// Default: 0.50 (at least 50% must be burned)
	MinBurnRatio cosmossdk_io_math.LegacyDec `protobuf:"bytes,12,opt,name=min_burn_ratio,json=minBurnRatio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_burn_ratio"`
	// max_burn_ratio is the maximum allowed burn ratio (governance bound)
	// Default: 0.90 (at most 90% can be burned, at least 10% to rewards)
	MaxBurnRatio cosmossdk_io_math.LegacyDec `protobuf:"bytes,13,opt,name=max_burn_ratio,json=maxBurnRatio,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"max_burn_ratio"`
	// LAYER 1: Base Fee Model
	// base_submission_fee is the static base fee for all submissions (before multipliers)
	// Default: 30000uomni (0.03 OMNI)
	// Split: 50% burned, 50% to reward pool
	BaseSubmissionFee github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,19,opt,name=base_submission_fee,json=baseSubmissionFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"base_submission_fee"`
	// LAYER 2: Epoch-Adaptive Fee Model (Dynamic Congestion Fee)
	// target_submissions_per_block is the target number of submissions per block
	// Used to calculate dynamic congestion multiplier
	// Default: 5
	TargetSubmissionsPerBlock uint32 `protobuf:"varint,20,opt,name=target_submissions_per_block,json=targetSubmissionsPerBlock,proto3" json:"target_submissions_per_block,omitempty"`
	// LAYER 3: C-Score Weighted Discount Model
	// max_cscore_discount is the maximum discount available based on C-Score
	// Default: 0.90 (90% discount cap for C-Score 1000)
	// C-Score range: 0-1000
	MaxCscoreDiscount cosmossdk_io_math.LegacyDec `protobuf:"bytes,21,opt,name=max_cscore_discount,json=maxCscoreDiscount,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"max_cscore_discount"`
	// minimum_submission_fee is the absolute floor for fees after all discounts
	// Ensures fees never drop below a minimum viable amount
	// Default: 3000uomni (0.003 OMNI)
	MinimumSubmissionFee github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,22,opt,name=minimum_submission_fee,json=minimumSubmissionFee,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"minimum_submission_fee"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_090c909664d3187a, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxPerBlock() uint32 {
	if m != nil {
		return m.MaxPerBlock
	}
	return 0
}

func (m *Params) GetTiers() []Tier {
	if m != nil {
		return m.Tiers
	}
	return nil
}

func (m *Params) GetRewardDenom() string {
	if m != nil {
		return m.RewardDenom
	}
	return ""
}

func (m *Params) GetMaxContributionsToKeep() uint64 {
	if m != nil {
		return m.MaxContributionsToKeep
	}
	return 0
}

func (m *Params) GetTargetSubmissionsPerBlock() uint32 {
	if m != nil {
		return m.TargetSubmissionsPerBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*Tier)(nil), "pos.poc.v1.Tier")
	proto.RegisterType((*Params)(nil), "pos.poc.v1.Params")
}

func init() { proto.RegisterFile("pos/poc/v1/params.proto", fileDescriptor_090c909664d3187a) }

var fileDescriptor_090c909664d3187a = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xc7, 0xe3, 0xdb, 0x34, 0xf7, 0x76, 0xd2, 0xa4, 0xe9, 0xa4, 0xed, 0x75, 0x7a, 0xaf, 0xd2,
	0xd0, 0x0d, 0xe1, 0xa3, 0xb6, 0x0a, 0x2b, 0xd8, 0x20, 0xa5, 0x11, 0x52, 0x05, 0x8b, 0xc8, 0x6d,
	0x41, 0xaa, 0x84, 0xac, 0xb1, 0x33, 0x49, 0x47, 0xe9, 0xcc, 0x98, 0x99, 0x71, 0x71, 0x5f, 0x81,
	0x15, 0x8f, 0xc0, 0x23, 0xb0, 0xe0, 0x21, 0xba, 0xac, 0x58, 0x21, 0x16, 0x15, 0x6a, 0x17, 0xb0,
	0xe7, 0x05, 0xd0, 0x8c, 0xad, 0xc6, 0x09, 0x3b, 0x6f, 0x92, 0xf1, 0x39, 0x33, 0xbf, 0x73, 0xce,
	0x7f, 0x7c, 0x7c, 0xc0, 0xbf, 0x11, 0x97, 0x6e, 0xc4, 0x43, 0xf7, 0x6c, 0xd7, 0x8d, 0x90, 0x40,
	0x54, 0x3a, 0x91, 0xe0, 0x8a, 0x43, 0x10, 0x71, 0xe9, 0x44, 0x3c, 0x74, 0xce, 0x76, 0x37, 0x57,
	0x11, 0x25, 0x8c, 0xbb, 0xe6, 0x37, 0x75, 0x6f, 0xae, 0x8d, 0xf9, 0x98, 0x9b, 0xa5, 0xab, 0x57,
	0x99, 0xb5, 0x15, 0x72, 0x49, 0xb9, 0xf4, 0x53, 0x47, 0xfa, 0x90, 0xba, 0xb6, 0x7d, 0x50, 0x3e,
	0x24, 0x58, 0x40, 0x08, 0xca, 0x0c, 0x51, 0x6c, 0x5b, 0x1d, 0xab, 0xbb, 0xe4, 0x99, 0x35, 0xdc,
	0x03, 0x95, 0x30, 0x56, 0x7c, 0x34, 0xb2, 0xff, 0xd2, 0xd6, 0xde, 0x83, 0x8b, 0xab, 0xad, 0xd2,
	0xb7, 0xab, 0xad, 0xf5, 0x94, 0x20, 0x87, 0x13, 0x87, 0x70, 0x97, 0x22, 0x75, 0xe2, 0xec, 0x33,
	0xf5, 0xe5, 0xf3, 0x0e, 0xc8, 0xd0, 0xfb, 0x4c, 0x79, 0xd9, 0xd1, 0xed, 0x5f, 0x00, 0x54, 0x06,
	0xa6, 0x02, 0x38, 0x00, 0xe0, 0x6d, 0xcc, 0x45, 0x4c, 0xfd, 0x28, 0x54, 0x69, 0xa4, 0xde, 0x6e,
	0xc6, 0xfc, 0xef, 0x4f, 0xe6, 0x4b, 0x3c, 0x46, 0xe1, 0x79, 0x1f, 0x87, 0x39, 0x72, 0x1f, 0x87,
	0xde, 0x52, 0x0a, 0x19, 0x84, 0x0a, 0x1e, 0x81, 0x46, 0x80, 0x24, 0xf6, 0x05, 0x7e, 0x87, 0xc4,
	0xd0, 0x8f, 0x19, 0x51, 0x45, 0x72, 0xad, 0x6b, 0x88, 0x67, 0x18, 0x47, 0x8c, 0x28, 0x78, 0x0c,
	0x56, 0x08, 0x1b, 0x9d, 0x22, 0x45, 0x38, 0xf3, 0xe5, 0x09, 0x12, 0xd8, 0x5e, 0x28, 0x9a, 0x6d,
	0xfd, 0x96, 0x74, 0xa0, 0x41, 0x70, 0x1b, 0xd4, 0x28, 0x4a, 0xfc, 0x08, 0x0b, 0x3f, 0x38, 0xe5,
	0xe1, 0xc4, 0x2e, 0x77, 0xac, 0x6e, 0xcd, 0xab, 0x52, 0x94, 0x0c, 0xb0, 0xe8, 0x69, 0x13, 0x7c,
	0x08, 0x16, 0x15, 0xc1, 0x42, 0xda, 0x8b, 0x9d, 0x85, 0x6e, 0xf5, 0x51, 0xc3, 0x99, 0x5e, 0xba,
	0xa3, 0x6f, 0xab, 0x57, 0xd6, 0x79, 0x78, 0xe9, 0x26, 0x78, 0x07, 0x2c, 0x67, 0xf5, 0x0f, 0x31,
	0xe3, 0xd4, 0xae, 0x98, 0x2b, 0xac, 0xa6, 0xb6, 0xbe, 0x36, 0xc1, 0x27, 0xa0, 0xa5, 0x83, 0x86,
	0x9c, 0x29, 0x41, 0x82, 0x58, 0x67, 0x23, 0x7d, 0xc5, 0xfd, 0x09, 0xc6, 0x91, 0xfd, 0x77, 0xc7,
	0xea, 0x96, 0xbd, 0x0d, 0x8a, 0x92, 0xbd, 0xbc, 0xff, 0x90, 0xbf, 0xc0, 0x38, 0x82, 0xaf, 0x40,
	0x5d, 0xc6, 0x01, 0x25, 0x52, 0x6a, 0x31, 0x46, 0x18, 0xdb, 0xff, 0x18, 0x29, 0xdc, 0x4c, 0x8a,
	0xbb, 0x63, 0xa2, 0x4e, 0xe2, 0xc0, 0x09, 0x39, 0xcd, 0xde, 0xac, 0xec, 0x6f, 0x47, 0x0e, 0x27,
	0xae, 0x3a, 0x8f, 0xb0, 0x74, 0xf6, 0x38, 0x61, 0x5e, 0x6d, 0x8a, 0x79, 0x8e, 0x31, 0xc4, 0x60,
	0x3d, 0xc7, 0x0d, 0x62, 0xc1, 0x7c, 0xa1, 0x65, 0xb2, 0x97, 0x8a, 0x2a, 0xdd, 0x9c, 0xf2, 0x7a,
	0xb1, 0x60, 0x9e, 0xa6, 0xc1, 0x37, 0x00, 0x52, 0xc2, 0xfc, 0xb9, 0x12, 0x40, 0xb1, 0x12, 0x1a,
	0x94, 0xb0, 0x83, 0x99, 0x2a, 0x34, 0x1e, 0x25, 0xf3, 0xf8, 0x6a, 0x51, 0x3c, 0x4a, 0x66, 0xf1,
	0xaf, 0x41, 0x5d, 0x67, 0x9f, 0x53, 0x67, 0xb9, 0xa8, 0x3a, 0xcb, 0x94, 0xe4, 0x64, 0xd1, 0x60,
	0x94, 0xe4, 0xc1, 0xb5, 0xe2, 0x60, 0x94, 0x4c, 0xc1, 0x3e, 0x68, 0x9a, 0x8e, 0x9c, 0x53, 0xa4,
	0x59, 0x4c, 0x91, 0x55, 0xcd, 0x9a, 0x95, 0xe4, 0x19, 0xf8, 0x5f, 0x21, 0x31, 0xc6, 0x2a, 0x17,
	0x42, 0xe6, 0xda, 0x69, 0xcd, 0xb4, 0x53, 0x2b, 0xdd, 0x33, 0x3d, 0x2a, 0x6f, 0x9b, 0x0b, 0x81,
	0xa6, 0xe9, 0x05, 0x19, 0x72, 0x81, 0xfd, 0x21, 0x91, 0x21, 0x8f, 0x99, 0xb2, 0xd7, 0x8b, 0xd6,
	0xbf, 0xaa, 0x1b, 0xc7, 0xc0, 0xfa, 0x19, 0x0b, 0x62, 0xb0, 0x41, 0x09, 0x23, 0x34, 0xa6, 0xf3,
	0x3a, 0x6c, 0x14, 0xd3, 0x61, 0x2d, 0xc3, 0xcd, 0x48, 0xf1, 0xb4, 0xf5, 0xf3, 0xe3, 0x96, 0xf5,
	0xfe, 0xc7, 0xa7, 0xfb, 0x0d, 0x3d, 0x2d, 0x12, 0x33, 0x2f, 0xd2, 0x4f, 0x6d, 0xef, 0xde, 0xc5,
	0x75, 0xdb, 0xba, 0xbc, 0x6e, 0x5b, 0xdf, 0xaf, 0xdb, 0xd6, 0x87, 0x9b, 0x76, 0xe9, 0xf2, 0xa6,
	0x5d, 0xfa, 0x7a, 0xd3, 0x2e, 0x1d, 0xaf, 0x4c, 0xf7, 0x9a, 0x00, 0x41, 0xc5, 0x0c, 0x82, 0xc7,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x03, 0x14, 0xa6, 0xa8, 0x73, 0x06, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.QuorumPct.Equal(that1.QuorumPct) {
		return false
	}
	if !this.BaseRewardUnit.Equal(that1.BaseRewardUnit) {
		return false
	}
	if !this.InflationShare.Equal(that1.InflationShare) {
		return false
	}
	if this.MaxPerBlock != that1.MaxPerBlock {
		return false
	}
	if len(this.Tiers) != len(that1.Tiers) {
		return false
	}
	for i := range this.Tiers {
		if !this.Tiers[i].Equal(&that1.Tiers[i]) {
			return false
		}
	}
	if this.RewardDenom != that1.RewardDenom {
		return false
	}
	if this.MaxContributionsToKeep != that1.MaxContributionsToKeep {
		return false
	}
	if !this.SubmissionFee.Equal(that1.SubmissionFee) {
		return false
	}
	if !this.SubmissionBurnRatio.Equal(that1.SubmissionBurnRatio) {
		return false
	}
	if !this.MinSubmissionFee.Equal(that1.MinSubmissionFee) {
		return false
	}
	if !this.MaxSubmissionFee.Equal(that1.MaxSubmissionFee) {
		return false
	}
	if !this.MinBurnRatio.Equal(that1.MinBurnRatio) {
		return false
	}
	if !this.MaxBurnRatio.Equal(that1.MaxBurnRatio) {
		return false
	}
	if !this.BaseSubmissionFee.Equal(that1.BaseSubmissionFee) {
		return false
	}
	if this.TargetSubmissionsPerBlock != that1.TargetSubmissionsPerBlock {
		return false
	}
	if !this.MaxCscoreDiscount.Equal(that1.MaxCscoreDiscount) {
		return false
	}
	if !this.MinimumSubmissionFee.Equal(that1.MinimumSubmissionFee) {
		return false
	}
	return true
}
func (m *Tier) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Tier) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Tier) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Cutoff.Size()
		i -= size
		if _, err := m.Cutoff.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MinimumSubmissionFee.Size()
		i -= size
		if _, err := m.MinimumSubmissionFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xb2
	{
		size := m.MaxCscoreDiscount.Size()
		i -= size
		if _, err := m.MaxCscoreDiscount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xaa
	if m.TargetSubmissionsPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TargetSubmissionsPerBlock))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	{
		size := m.BaseSubmissionFee.Size()
		i -= size
		if _, err := m.BaseSubmissionFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x9a
	{
		size := m.MaxBurnRatio.Size()
		i -= size
		if _, err := m.MaxBurnRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	{
		size := m.MinBurnRatio.Size()
		i -= size
		if _, err := m.MinBurnRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	{
		size := m.MaxSubmissionFee.Size()
		i -= size
		if _, err := m.MaxSubmissionFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size := m.MinSubmissionFee.Size()
		i -= size
		if _, err := m.MinSubmissionFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size := m.SubmissionBurnRatio.Size()
		i -= size
		if _, err := m.SubmissionBurnRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.SubmissionFee.Size()
		i -= size
		if _, err := m.SubmissionFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.MaxContributionsToKeep != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxContributionsToKeep))
		i--
		dAtA[i] = 0x38
	}
	if len(m.RewardDenom) > 0 {
		i -= len(m.RewardDenom)
		copy(dAtA[i:], m.RewardDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.RewardDenom)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Tiers) > 0 {
		for iNdEx := len(m.Tiers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tiers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.MaxPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxPerBlock))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.InflationShare.Size()
		i -= size
		if _, err := m.InflationShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.BaseRewardUnit.Size()
		i -= size
		if _, err := m.BaseRewardUnit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.QuorumPct.Size()
		i -= size
		if _, err := m.QuorumPct.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Tier) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.Cutoff.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.QuorumPct.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BaseRewardUnit.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.InflationShare.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MaxPerBlock != 0 {
		n += 1 + sovParams(uint64(m.MaxPerBlock))
	}
	if len(m.Tiers) > 0 {
		for _, e := range m.Tiers {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = len(m.RewardDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MaxContributionsToKeep != 0 {
		n += 1 + sovParams(uint64(m.MaxContributionsToKeep))
	}
	l = m.SubmissionFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.SubmissionBurnRatio.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinSubmissionFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxSubmissionFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinBurnRatio.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxBurnRatio.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BaseSubmissionFee.Size()
	n += 2 + l + sovParams(uint64(l))
	if m.TargetSubmissionsPerBlock != 0 {
		n += 2 + sovParams(uint64(m.TargetSubmissionsPerBlock))
	}
	l = m.MaxCscoreDiscount.Size()
	n += 2 + l + sovParams(uint64(l))
	l = m.MinimumSubmissionFee.Size()
	n += 2 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Tier) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Tier: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Tier: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cutoff", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Cutoff.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuorumPct", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.QuorumPct.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseRewardUnit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseRewardUnit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InflationShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InflationShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPerBlock", wireType)
			}
			m.MaxPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPerBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tiers = append(m.Tiers, Tier{})
			if err := m.Tiers[len(m.Tiers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxContributionsToKeep", wireType)
			}
			m.MaxContributionsToKeep = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxContributionsToKeep |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmissionFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SubmissionFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmissionBurnRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SubmissionBurnRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSubmissionFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinSubmissionFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSubmissionFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxSubmissionFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBurnRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinBurnRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBurnRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxBurnRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseSubmissionFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseSubmissionFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetSubmissionsPerBlock", wireType)
			}
			m.TargetSubmissionsPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetSubmissionsPerBlock |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCscoreDiscount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxCscoreDiscount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumSubmissionFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumSubmissionFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
