"""Validator Setup Request Model."""

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import Column, String, Float, DateTime, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID
import enum

from app.db.base_class import Base


class RunMode(str, enum.Enum):
    """Validator run mode."""
    CLOUD = "cloud"
    LOCAL = "local"


class Provider(str, enum.Enum):
    """Cloud provider type."""
    OMNIPHI_CLOUD = "omniphi_cloud"
    AWS = "aws"
    GCP = "gcp"
    DIGITAL_OCEAN = "digital_ocean"
    AKASH = "akash"
    LOCAL = "local"


class SetupStatus(str, enum.Enum):
    """Setup request status."""
    PENDING = "pending"
    PROVISIONING = "provisioning"
    CONFIGURING = "configuring"
    READY_FOR_CHAIN_TX = "ready_for_chain_tx"
    ACTIVE = "active"
    READY = "ready"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class ValidatorSetupRequest(Base):
    """Validator setup request table."""

    __tablename__ = "validator_setup_requests"

    # Primary key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)

    # Wallet and identity
    wallet_address = Column(String, nullable=False, index=True)
    validator_name = Column(String, nullable=False)
    website = Column(String, nullable=True)
    description = Column(String, nullable=True)

    # Commission
    commission_rate = Column(Float, nullable=False)  # e.g., 0.10 for 10%

    # Deployment config
    run_mode = Column(SQLEnum(RunMode), nullable=False)
    provider = Column(SQLEnum(Provider), nullable=False)

    # Consensus key (generated by node)
    consensus_pubkey = Column(String, nullable=True)  # Will be populated after provisioning

    # Status tracking
    status = Column(SQLEnum(SetupStatus), nullable=False, default=SetupStatus.PENDING)
    error_message = Column(String, nullable=True)

    # Timestamps
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    def __repr__(self):
        return f"<ValidatorSetupRequest {self.validator_name} ({self.wallet_address})>"
