// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pos/poc/v1/fee_metrics.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FeeMetrics tracks cumulative fee burn statistics for the PoC module
// This provides transparency and audit trail for fee collection and burning
type FeeMetrics struct {
	// total_fees_collected is the cumulative amount of submission fees collected
	TotalFeesCollected github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=total_fees_collected,json=totalFeesCollected,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_fees_collected"`
	// total_burned is the cumulative amount burned from submission fees
	TotalBurned github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=total_burned,json=totalBurned,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_burned"`
	// total_reward_redirect is the cumulative amount sent to PoC reward pool
	TotalRewardRedirect github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=total_reward_redirect,json=totalRewardRedirect,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_reward_redirect"`
	// last_updated_height is the block height when metrics were last updated
	LastUpdatedHeight int64 `protobuf:"varint,4,opt,name=last_updated_height,json=lastUpdatedHeight,proto3" json:"last_updated_height,omitempty"`
}

func (m *FeeMetrics) Reset()         { *m = FeeMetrics{} }
func (m *FeeMetrics) String() string { return proto.CompactTextString(m) }
func (*FeeMetrics) ProtoMessage()    {}
func (*FeeMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_f277252a795b6df9, []int{0}
}
func (m *FeeMetrics) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeMetrics.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeMetrics.Merge(m, src)
}
func (m *FeeMetrics) XXX_Size() int {
	return m.Size()
}
func (m *FeeMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_FeeMetrics proto.InternalMessageInfo

func (m *FeeMetrics) GetTotalFeesCollected() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalFeesCollected
	}
	return nil
}

func (m *FeeMetrics) GetTotalBurned() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalBurned
	}
	return nil
}

func (m *FeeMetrics) GetTotalRewardRedirect() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalRewardRedirect
	}
	return nil
}

func (m *FeeMetrics) GetLastUpdatedHeight() int64 {
	if m != nil {
		return m.LastUpdatedHeight
	}
	return 0
}

// ContributorFeeStats tracks per-contributor fee statistics
// This enables analytics on contributor behavior and fee rebate mechanisms
type ContributorFeeStats struct {
	// address is the contributor's address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// total_fees_paid is the total fees paid by this contributor
	TotalFeesPaid github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=total_fees_paid,json=totalFeesPaid,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_fees_paid"`
	// total_burned is the total amount burned from this contributor's fees
	TotalBurned github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=total_burned,json=totalBurned,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_burned"`
	// submission_count is the total number of submissions by this contributor
	SubmissionCount uint64 `protobuf:"varint,4,opt,name=submission_count,json=submissionCount,proto3" json:"submission_count,omitempty"`
	// first_submission_height is the block height of first submission
	FirstSubmissionHeight int64 `protobuf:"varint,5,opt,name=first_submission_height,json=firstSubmissionHeight,proto3" json:"first_submission_height,omitempty"`
	// last_submission_height is the block height of most recent submission
	LastSubmissionHeight int64 `protobuf:"varint,6,opt,name=last_submission_height,json=lastSubmissionHeight,proto3" json:"last_submission_height,omitempty"`
}

func (m *ContributorFeeStats) Reset()         { *m = ContributorFeeStats{} }
func (m *ContributorFeeStats) String() string { return proto.CompactTextString(m) }
func (*ContributorFeeStats) ProtoMessage()    {}
func (*ContributorFeeStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_f277252a795b6df9, []int{1}
}
func (m *ContributorFeeStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContributorFeeStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContributorFeeStats.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContributorFeeStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContributorFeeStats.Merge(m, src)
}
func (m *ContributorFeeStats) XXX_Size() int {
	return m.Size()
}
func (m *ContributorFeeStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ContributorFeeStats.DiscardUnknown(m)
}

var xxx_messageInfo_ContributorFeeStats proto.InternalMessageInfo

func (m *ContributorFeeStats) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ContributorFeeStats) GetTotalFeesPaid() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalFeesPaid
	}
	return nil
}

func (m *ContributorFeeStats) GetTotalBurned() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalBurned
	}
	return nil
}

func (m *ContributorFeeStats) GetSubmissionCount() uint64 {
	if m != nil {
		return m.SubmissionCount
	}
	return 0
}

func (m *ContributorFeeStats) GetFirstSubmissionHeight() int64 {
	if m != nil {
		return m.FirstSubmissionHeight
	}
	return 0
}

func (m *ContributorFeeStats) GetLastSubmissionHeight() int64 {
	if m != nil {
		return m.LastSubmissionHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*FeeMetrics)(nil), "pos.poc.v1.FeeMetrics")
	proto.RegisterType((*ContributorFeeStats)(nil), "pos.poc.v1.ContributorFeeStats")
}

func init() { proto.RegisterFile("pos/poc/v1/fee_metrics.proto", fileDescriptor_f277252a795b6df9) }

var fileDescriptor_f277252a795b6df9 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x63, 0x5c, 0x8a, 0xb8, 0x82, 0x4a, 0x9d, 0x14, 0x4c, 0x45, 0x9d, 0xa8, 0x03, 0x4a,
	0x91, 0xb0, 0x09, 0x20, 0x86, 0x8e, 0x89, 0x14, 0xb1, 0x20, 0x21, 0x57, 0x2c, 0x2c, 0xd6, 0xf9,
	0xfc, 0x92, 0x9c, 0x48, 0xfc, 0xac, 0x7b, 0xe7, 0x00, 0x03, 0x62, 0x67, 0xe2, 0x23, 0x30, 0x33,
	0xf1, 0x31, 0x2a, 0xb1, 0x74, 0x41, 0x62, 0x02, 0x94, 0x0c, 0xf0, 0x31, 0x90, 0xef, 0x92, 0xa6,
	0xa2, 0x8c, 0xed, 0x92, 0x9c, 0xef, 0xaf, 0xff, 0xfb, 0xc9, 0xf7, 0x3b, 0xb3, 0x3b, 0x05, 0x52,
	0x54, 0xa0, 0x88, 0xa6, 0x9d, 0x68, 0x00, 0x90, 0x4c, 0x40, 0x2b, 0x29, 0x28, 0x2c, 0x14, 0x6a,
	0xf4, 0x58, 0x81, 0x14, 0x16, 0x28, 0xc2, 0x69, 0x67, 0x67, 0x8b, 0x4f, 0x64, 0x8e, 0x91, 0xf9,
	0xb5, 0xf1, 0x4e, 0x63, 0x88, 0x43, 0x34, 0xcb, 0xa8, 0x5a, 0x2d, 0x76, 0x03, 0x81, 0x34, 0x41,
	0x8a, 0x52, 0x4e, 0x10, 0x4d, 0x3b, 0x29, 0x68, 0xde, 0x89, 0x04, 0xca, 0xdc, 0xe6, 0x7b, 0x5f,
	0x5d, 0xc6, 0xfa, 0x00, 0xcf, 0x2c, 0xc9, 0x7b, 0xc7, 0x1a, 0x1a, 0x35, 0x1f, 0x27, 0x03, 0x00,
	0x4a, 0x04, 0x8e, 0xc7, 0x20, 0x34, 0x64, 0xbe, 0xd3, 0x72, 0xdb, 0x1b, 0x0f, 0x6f, 0x87, 0x76,
	0x5a, 0x58, 0x4d, 0x0b, 0x17, 0xd3, 0xc2, 0x1e, 0xca, 0xbc, 0xfb, 0xe0, 0xe8, 0x47, 0xb3, 0xf6,
	0xf9, 0x67, 0xb3, 0x3d, 0x94, 0x7a, 0x54, 0xa6, 0xa1, 0xc0, 0x49, 0xb4, 0x40, 0xdb, 0xbf, 0xfb,
	0x94, 0xbd, 0x8a, 0xf4, 0xdb, 0x02, 0xc8, 0x14, 0x28, 0xf6, 0x0c, 0xa8, 0x0f, 0x40, 0xbd, 0x25,
	0xc6, 0xcb, 0xd9, 0x35, 0x8b, 0x4f, 0x4b, 0x95, 0x43, 0xe6, 0x5f, 0x3a, 0x7f, 0xec, 0x86, 0x01,
	0x74, 0xcd, 0x7c, 0xef, 0x3d, 0xdb, 0xb6, 0x3c, 0x05, 0xaf, 0xb9, 0xca, 0x12, 0x05, 0x99, 0x54,
	0x20, 0xb4, 0xef, 0x9e, 0x3f, 0xb8, 0x6e, 0x48, 0xb1, 0x01, 0xc5, 0x0b, 0x8e, 0x17, 0xb2, 0xfa,
	0x98, 0x93, 0x4e, 0xca, 0x22, 0xe3, 0x1a, 0xb2, 0x64, 0x04, 0x72, 0x38, 0xd2, 0xfe, 0x5a, 0xcb,
	0x69, 0xbb, 0xf1, 0x56, 0x15, 0xbd, 0xb0, 0xc9, 0x53, 0x13, 0x1c, 0xec, 0xfe, 0xf9, 0xd4, 0x74,
	0x3e, 0xfc, 0xfe, 0x72, 0xaf, 0x51, 0x5d, 0x95, 0x37, 0xe6, 0xb2, 0xac, 0xf4, 0xed, 0x7d, 0x73,
	0x59, 0xbd, 0x87, 0xb9, 0x56, 0x32, 0x2d, 0x35, 0xaa, 0x3e, 0xc0, 0xa1, 0xe6, 0x9a, 0x3c, 0x9f,
	0x5d, 0xe1, 0x59, 0xa6, 0x80, 0xc8, 0x77, 0x5a, 0x4e, 0xfb, 0x6a, 0xbc, 0x7c, 0xf4, 0x88, 0x6d,
	0x9e, 0x12, 0x5e, 0x70, 0x79, 0x21, 0x87, 0x7e, 0xfd, 0xc4, 0xf5, 0x73, 0x2e, 0xcf, 0x6a, 0x76,
	0x2f, 0x58, 0xf3, 0x3e, 0xbb, 0x41, 0x65, 0x3a, 0x91, 0x44, 0x12, 0xf3, 0x44, 0x60, 0x99, 0xdb,
	0x23, 0x5e, 0x8b, 0x37, 0x57, 0xfb, 0xbd, 0x6a, 0xdb, 0x7b, 0xc2, 0x6e, 0x0d, 0xa4, 0x22, 0x9d,
	0x9c, 0x2a, 0x2c, 0xa4, 0x5c, 0x36, 0x52, 0xb6, 0x4d, 0x7c, 0x78, 0x92, 0x5a, 0x31, 0xde, 0x63,
	0x76, 0xd3, 0x88, 0x3c, 0x5b, 0x5b, 0x37, 0xb5, 0x46, 0x95, 0xfe, 0xdb, 0x3a, 0xb8, 0xbb, 0xd4,
	0xb9, 0xbb, 0xd2, 0xf9, 0x1f, 0x7f, 0xdd, 0xfd, 0xa3, 0x59, 0xe0, 0x1c, 0xcf, 0x02, 0xe7, 0xd7,
	0x2c, 0x70, 0x3e, 0xce, 0x83, 0xda, 0xf1, 0x3c, 0xa8, 0x7d, 0x9f, 0x07, 0xb5, 0x97, 0x9b, 0xab,
	0xa2, 0x79, 0xfd, 0x74, 0xdd, 0x7c, 0xd7, 0x8f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x25,
	0x13, 0x9b, 0x4c, 0x04, 0x00, 0x00,
}

func (this *FeeMetrics) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FeeMetrics)
	if !ok {
		that2, ok := that.(FeeMetrics)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.TotalFeesCollected) != len(that1.TotalFeesCollected) {
		return false
	}
	for i := range this.TotalFeesCollected {
		if !this.TotalFeesCollected[i].Equal(&that1.TotalFeesCollected[i]) {
			return false
		}
	}
	if len(this.TotalBurned) != len(that1.TotalBurned) {
		return false
	}
	for i := range this.TotalBurned {
		if !this.TotalBurned[i].Equal(&that1.TotalBurned[i]) {
			return false
		}
	}
	if len(this.TotalRewardRedirect) != len(that1.TotalRewardRedirect) {
		return false
	}
	for i := range this.TotalRewardRedirect {
		if !this.TotalRewardRedirect[i].Equal(&that1.TotalRewardRedirect[i]) {
			return false
		}
	}
	if this.LastUpdatedHeight != that1.LastUpdatedHeight {
		return false
	}
	return true
}
func (this *ContributorFeeStats) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ContributorFeeStats)
	if !ok {
		that2, ok := that.(ContributorFeeStats)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	if len(this.TotalFeesPaid) != len(that1.TotalFeesPaid) {
		return false
	}
	for i := range this.TotalFeesPaid {
		if !this.TotalFeesPaid[i].Equal(&that1.TotalFeesPaid[i]) {
			return false
		}
	}
	if len(this.TotalBurned) != len(that1.TotalBurned) {
		return false
	}
	for i := range this.TotalBurned {
		if !this.TotalBurned[i].Equal(&that1.TotalBurned[i]) {
			return false
		}
	}
	if this.SubmissionCount != that1.SubmissionCount {
		return false
	}
	if this.FirstSubmissionHeight != that1.FirstSubmissionHeight {
		return false
	}
	if this.LastSubmissionHeight != that1.LastSubmissionHeight {
		return false
	}
	return true
}
func (m *FeeMetrics) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeMetrics) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeMetrics) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUpdatedHeight != 0 {
		i = encodeVarintFeeMetrics(dAtA, i, uint64(m.LastUpdatedHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TotalRewardRedirect) > 0 {
		for iNdEx := len(m.TotalRewardRedirect) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalRewardRedirect[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeeMetrics(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.TotalBurned) > 0 {
		for iNdEx := len(m.TotalBurned) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalBurned[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeeMetrics(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.TotalFeesCollected) > 0 {
		for iNdEx := len(m.TotalFeesCollected) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalFeesCollected[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeeMetrics(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ContributorFeeStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContributorFeeStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContributorFeeStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastSubmissionHeight != 0 {
		i = encodeVarintFeeMetrics(dAtA, i, uint64(m.LastSubmissionHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.FirstSubmissionHeight != 0 {
		i = encodeVarintFeeMetrics(dAtA, i, uint64(m.FirstSubmissionHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.SubmissionCount != 0 {
		i = encodeVarintFeeMetrics(dAtA, i, uint64(m.SubmissionCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TotalBurned) > 0 {
		for iNdEx := len(m.TotalBurned) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalBurned[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeeMetrics(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.TotalFeesPaid) > 0 {
		for iNdEx := len(m.TotalFeesPaid) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalFeesPaid[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeeMetrics(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintFeeMetrics(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFeeMetrics(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeeMetrics(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeMetrics) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TotalFeesCollected) > 0 {
		for _, e := range m.TotalFeesCollected {
			l = e.Size()
			n += 1 + l + sovFeeMetrics(uint64(l))
		}
	}
	if len(m.TotalBurned) > 0 {
		for _, e := range m.TotalBurned {
			l = e.Size()
			n += 1 + l + sovFeeMetrics(uint64(l))
		}
	}
	if len(m.TotalRewardRedirect) > 0 {
		for _, e := range m.TotalRewardRedirect {
			l = e.Size()
			n += 1 + l + sovFeeMetrics(uint64(l))
		}
	}
	if m.LastUpdatedHeight != 0 {
		n += 1 + sovFeeMetrics(uint64(m.LastUpdatedHeight))
	}
	return n
}

func (m *ContributorFeeStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovFeeMetrics(uint64(l))
	}
	if len(m.TotalFeesPaid) > 0 {
		for _, e := range m.TotalFeesPaid {
			l = e.Size()
			n += 1 + l + sovFeeMetrics(uint64(l))
		}
	}
	if len(m.TotalBurned) > 0 {
		for _, e := range m.TotalBurned {
			l = e.Size()
			n += 1 + l + sovFeeMetrics(uint64(l))
		}
	}
	if m.SubmissionCount != 0 {
		n += 1 + sovFeeMetrics(uint64(m.SubmissionCount))
	}
	if m.FirstSubmissionHeight != 0 {
		n += 1 + sovFeeMetrics(uint64(m.FirstSubmissionHeight))
	}
	if m.LastSubmissionHeight != 0 {
		n += 1 + sovFeeMetrics(uint64(m.LastSubmissionHeight))
	}
	return n
}

func sovFeeMetrics(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeeMetrics(x uint64) (n int) {
	return sovFeeMetrics(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeMetrics) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeeMetrics
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeMetrics: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeMetrics: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalFeesCollected", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalFeesCollected = append(m.TotalFeesCollected, types.Coin{})
			if err := m.TotalFeesCollected[len(m.TotalFeesCollected)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBurned", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalBurned = append(m.TotalBurned, types.Coin{})
			if err := m.TotalBurned[len(m.TotalBurned)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRewardRedirect", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalRewardRedirect = append(m.TotalRewardRedirect, types.Coin{})
			if err := m.TotalRewardRedirect[len(m.TotalRewardRedirect)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdatedHeight", wireType)
			}
			m.LastUpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeeMetrics(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContributorFeeStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeeMetrics
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContributorFeeStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContributorFeeStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalFeesPaid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalFeesPaid = append(m.TotalFeesPaid, types.Coin{})
			if err := m.TotalFeesPaid[len(m.TotalFeesPaid)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBurned", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalBurned = append(m.TotalBurned, types.Coin{})
			if err := m.TotalBurned[len(m.TotalBurned)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmissionCount", wireType)
			}
			m.SubmissionCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmissionCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstSubmissionHeight", wireType)
			}
			m.FirstSubmissionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstSubmissionHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSubmissionHeight", wireType)
			}
			m.LastSubmissionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastSubmissionHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeeMetrics(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeeMetrics(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeeMetrics
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeeMetrics
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeeMetrics
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeeMetrics
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeeMetrics        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeeMetrics          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeeMetrics = fmt.Errorf("proto: unexpected end of group")
)
