// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pos/poc/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the poc module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// contributions is the list of all contributions
	Contributions []Contribution `protobuf:"bytes,2,rep,name=contributions,proto3" json:"contributions"`
	// credits is the list of all credit balances
	Credits []Credits `protobuf:"bytes,3,rep,name=credits,proto3" json:"credits"`
	// next_contribution_id is the next ID to be assigned
	NextContributionId uint64 `protobuf:"varint,4,opt,name=next_contribution_id,json=nextContributionId,proto3" json:"next_contribution_id,omitempty"`
	// fee_metrics tracks cumulative fee burn statistics
	FeeMetrics FeeMetrics `protobuf:"bytes,5,opt,name=fee_metrics,json=feeMetrics,proto3" json:"fee_metrics"`
	// contributor_fee_stats is the list of per-contributor fee statistics
	ContributorFeeStats []ContributorFeeStats `protobuf:"bytes,6,rep,name=contributor_fee_stats,json=contributorFeeStats,proto3" json:"contributor_fee_stats"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3249f0e0ccd8dfce, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetContributions() []Contribution {
	if m != nil {
		return m.Contributions
	}
	return nil
}

func (m *GenesisState) GetCredits() []Credits {
	if m != nil {
		return m.Credits
	}
	return nil
}

func (m *GenesisState) GetNextContributionId() uint64 {
	if m != nil {
		return m.NextContributionId
	}
	return 0
}

func (m *GenesisState) GetFeeMetrics() FeeMetrics {
	if m != nil {
		return m.FeeMetrics
	}
	return FeeMetrics{}
}

func (m *GenesisState) GetContributorFeeStats() []ContributorFeeStats {
	if m != nil {
		return m.ContributorFeeStats
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "pos.poc.v1.GenesisState")
}

func init() { proto.RegisterFile("pos/poc/v1/genesis.proto", fileDescriptor_3249f0e0ccd8dfce) }

var fileDescriptor_3249f0e0ccd8dfce = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4e, 0x32, 0x31,
	0x14, 0x85, 0xa7, 0x3f, 0xfc, 0x18, 0x8b, 0xc6, 0x58, 0x50, 0x1b, 0xa2, 0x03, 0x71, 0x85, 0x2e,
	0x66, 0x04, 0xe2, 0x0b, 0xa0, 0xc1, 0xb8, 0x30, 0x31, 0xb8, 0xd2, 0xcd, 0x64, 0x18, 0x0a, 0xe9,
	0x82, 0xb9, 0x4d, 0x5b, 0x09, 0xbe, 0x85, 0xbe, 0x85, 0x4b, 0x1f, 0x83, 0x25, 0x4b, 0x57, 0xc6,
	0xc0, 0xc2, 0xd7, 0x30, 0xd3, 0x19, 0xb0, 0x24, 0x6c, 0x9a, 0xa6, 0xdf, 0x3d, 0xe7, 0xde, 0xd3,
	0x8b, 0xa9, 0x00, 0xe5, 0x0b, 0x88, 0xfc, 0x71, 0xc3, 0x1f, 0xb2, 0x98, 0x29, 0xae, 0x3c, 0x21,
	0x41, 0x03, 0xc1, 0x02, 0x94, 0x27, 0x20, 0xf2, 0xc6, 0x8d, 0xca, 0x7e, 0x38, 0xe2, 0x31, 0xf8,
	0xe6, 0x4c, 0x71, 0xa5, 0x3c, 0x84, 0x21, 0x98, 0xab, 0x9f, 0xdc, 0xb2, 0xd7, 0x23, 0xcb, 0x4e,
	0x84, 0x32, 0x1c, 0x65, 0x6e, 0x95, 0x13, 0x0b, 0x44, 0x10, 0x6b, 0xc9, 0x7b, 0xcf, 0x9a, 0x43,
	0x9c, 0xe1, 0x63, 0x0b, 0x0f, 0x18, 0x0b, 0x46, 0x4c, 0x4b, 0x1e, 0x65, 0xe2, 0xd3, 0xb7, 0x1c,
	0xde, 0xb9, 0x49, 0x87, 0x7b, 0xd0, 0xa1, 0x66, 0xe4, 0x12, 0x17, 0x52, 0x77, 0x8a, 0x6a, 0xa8,
	0x5e, 0x6c, 0x12, 0xef, 0x6f, 0x58, 0xef, 0xde, 0x90, 0xf6, 0xf6, 0xf4, 0xab, 0xea, 0xbc, 0xff,
	0x7c, 0x9c, 0xa3, 0x6e, 0x56, 0x4c, 0xae, 0xf1, 0xae, 0xdd, 0x5b, 0xd1, 0x7f, 0xb5, 0x5c, 0xbd,
	0xd8, 0xa4, 0xb6, 0xfa, 0xca, 0x2a, 0x68, 0xe7, 0x13, 0x8f, 0xee, 0xba, 0x88, 0xb4, 0xf0, 0x56,
	0x24, 0x59, 0x9f, 0x6b, 0x45, 0x73, 0x46, 0x5f, 0x5a, 0xd3, 0xa7, 0x28, 0x93, 0x2e, 0x2b, 0xc9,
	0x05, 0x2e, 0xc7, 0x6c, 0xa2, 0x03, 0xdb, 0x2a, 0xe0, 0x7d, 0x9a, 0xaf, 0xa1, 0x7a, 0xbe, 0x4b,
	0x12, 0x66, 0x77, 0xbe, 0xed, 0x93, 0x36, 0x2e, 0x5a, 0x3f, 0x41, 0xff, 0x9b, 0xa0, 0x87, 0x76,
	0xab, 0x0e, 0x63, 0x77, 0x29, 0xb5, 0xc3, 0xe2, 0xc1, 0xea, 0x99, 0x3c, 0xe2, 0x83, 0x55, 0x43,
	0x90, 0x41, 0xe2, 0xa7, 0x74, 0xa8, 0x15, 0x2d, 0x98, 0xc1, 0xab, 0x1b, 0x83, 0x83, 0xec, 0x30,
	0x96, 0xfc, 0xf3, 0x32, 0x44, 0x29, 0xda, 0x80, 0xce, 0xa6, 0x73, 0x17, 0xcd, 0xe6, 0x2e, 0xfa,
	0x9e, 0xbb, 0xe8, 0x75, 0xe1, 0x3a, 0xb3, 0x85, 0xeb, 0x7c, 0x2e, 0x5c, 0xe7, 0x69, 0x2f, 0xd9,
	0xe5, 0xc4, 0x6c, 0x53, 0xbf, 0x08, 0xa6, 0x7a, 0x05, 0xb3, 0xc5, 0xd6, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb1, 0x6f, 0x0c, 0x29, 0x6c, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContributorFeeStats) > 0 {
		for iNdEx := len(m.ContributorFeeStats) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ContributorFeeStats[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	{
		size, err := m.FeeMetrics.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.NextContributionId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextContributionId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Credits) > 0 {
		for iNdEx := len(m.Credits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Credits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Contributions) > 0 {
		for iNdEx := len(m.Contributions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Contributions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Contributions) > 0 {
		for _, e := range m.Contributions {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Credits) > 0 {
		for _, e := range m.Credits {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextContributionId != 0 {
		n += 1 + sovGenesis(uint64(m.NextContributionId))
	}
	l = m.FeeMetrics.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.ContributorFeeStats) > 0 {
		for _, e := range m.ContributorFeeStats {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contributions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contributions = append(m.Contributions, Contribution{})
			if err := m.Contributions[len(m.Contributions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Credits = append(m.Credits, Credits{})
			if err := m.Credits[len(m.Credits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextContributionId", wireType)
			}
			m.NextContributionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextContributionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeMetrics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeMetrics.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContributorFeeStats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContributorFeeStats = append(m.ContributorFeeStats, ContributorFeeStats{})
			if err := m.ContributorFeeStats[len(m.ContributorFeeStats)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
