// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pos/poc/v1/query.proto

package types

import (
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryContributionRequest is the request type for the Query/Contribution RPC method.
type QueryContributionRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryContributionRequest) Reset()         { *m = QueryContributionRequest{} }
func (m *QueryContributionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryContributionRequest) ProtoMessage()    {}
func (*QueryContributionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{2}
}
func (m *QueryContributionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContributionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContributionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContributionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContributionRequest.Merge(m, src)
}
func (m *QueryContributionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryContributionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContributionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContributionRequest proto.InternalMessageInfo

func (m *QueryContributionRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryContributionResponse is the response type for the Query/Contribution RPC method.
type QueryContributionResponse struct {
	Contribution Contribution `protobuf:"bytes,1,opt,name=contribution,proto3" json:"contribution"`
}

func (m *QueryContributionResponse) Reset()         { *m = QueryContributionResponse{} }
func (m *QueryContributionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryContributionResponse) ProtoMessage()    {}
func (*QueryContributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{3}
}
func (m *QueryContributionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContributionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContributionResponse.Merge(m, src)
}
func (m *QueryContributionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryContributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContributionResponse proto.InternalMessageInfo

func (m *QueryContributionResponse) GetContribution() Contribution {
	if m != nil {
		return m.Contribution
	}
	return Contribution{}
}

// QueryContributionsRequest is the request type for the Query/Contributions RPC method.
type QueryContributionsRequest struct {
	// contributor filters by contributor address (optional)
	Contributor string `protobuf:"bytes,1,opt,name=contributor,proto3" json:"contributor,omitempty"`
	// ctype filters by contribution type (optional)
	Ctype string `protobuf:"bytes,2,opt,name=ctype,proto3" json:"ctype,omitempty"`
	// verified filters by verification status (optional, -1 = all, 0 = unverified, 1 = verified)
	Verified int32 `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryContributionsRequest) Reset()         { *m = QueryContributionsRequest{} }
func (m *QueryContributionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryContributionsRequest) ProtoMessage()    {}
func (*QueryContributionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{4}
}
func (m *QueryContributionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContributionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContributionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContributionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContributionsRequest.Merge(m, src)
}
func (m *QueryContributionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryContributionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContributionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContributionsRequest proto.InternalMessageInfo

func (m *QueryContributionsRequest) GetContributor() string {
	if m != nil {
		return m.Contributor
	}
	return ""
}

func (m *QueryContributionsRequest) GetCtype() string {
	if m != nil {
		return m.Ctype
	}
	return ""
}

func (m *QueryContributionsRequest) GetVerified() int32 {
	if m != nil {
		return m.Verified
	}
	return 0
}

func (m *QueryContributionsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryContributionsResponse is the response type for the Query/Contributions RPC method.
type QueryContributionsResponse struct {
	Contributions []Contribution      `protobuf:"bytes,1,rep,name=contributions,proto3" json:"contributions"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryContributionsResponse) Reset()         { *m = QueryContributionsResponse{} }
func (m *QueryContributionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryContributionsResponse) ProtoMessage()    {}
func (*QueryContributionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{5}
}
func (m *QueryContributionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContributionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContributionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContributionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContributionsResponse.Merge(m, src)
}
func (m *QueryContributionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryContributionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContributionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContributionsResponse proto.InternalMessageInfo

func (m *QueryContributionsResponse) GetContributions() []Contribution {
	if m != nil {
		return m.Contributions
	}
	return nil
}

func (m *QueryContributionsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryCreditsRequest is the request type for the Query/Credits RPC method.
type QueryCreditsRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryCreditsRequest) Reset()         { *m = QueryCreditsRequest{} }
func (m *QueryCreditsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCreditsRequest) ProtoMessage()    {}
func (*QueryCreditsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{6}
}
func (m *QueryCreditsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCreditsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCreditsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCreditsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCreditsRequest.Merge(m, src)
}
func (m *QueryCreditsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCreditsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCreditsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCreditsRequest proto.InternalMessageInfo

func (m *QueryCreditsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryCreditsResponse is the response type for the Query/Credits RPC method.
type QueryCreditsResponse struct {
	Credits Credits `protobuf:"bytes,1,opt,name=credits,proto3" json:"credits"`
	Tier    string  `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
}

func (m *QueryCreditsResponse) Reset()         { *m = QueryCreditsResponse{} }
func (m *QueryCreditsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCreditsResponse) ProtoMessage()    {}
func (*QueryCreditsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{7}
}
func (m *QueryCreditsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCreditsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCreditsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCreditsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCreditsResponse.Merge(m, src)
}
func (m *QueryCreditsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCreditsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCreditsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCreditsResponse proto.InternalMessageInfo

func (m *QueryCreditsResponse) GetCredits() Credits {
	if m != nil {
		return m.Credits
	}
	return Credits{}
}

func (m *QueryCreditsResponse) GetTier() string {
	if m != nil {
		return m.Tier
	}
	return ""
}

// QueryFeeMetricsRequest is the request type for the Query/FeeMetrics RPC method.
type QueryFeeMetricsRequest struct {
}

func (m *QueryFeeMetricsRequest) Reset()         { *m = QueryFeeMetricsRequest{} }
func (m *QueryFeeMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFeeMetricsRequest) ProtoMessage()    {}
func (*QueryFeeMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{8}
}
func (m *QueryFeeMetricsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFeeMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFeeMetricsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFeeMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFeeMetricsRequest.Merge(m, src)
}
func (m *QueryFeeMetricsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFeeMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFeeMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFeeMetricsRequest proto.InternalMessageInfo

// QueryFeeMetricsResponse is the response type for the Query/FeeMetrics RPC method.
type QueryFeeMetricsResponse struct {
	Metrics FeeMetrics `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics"`
}

func (m *QueryFeeMetricsResponse) Reset()         { *m = QueryFeeMetricsResponse{} }
func (m *QueryFeeMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFeeMetricsResponse) ProtoMessage()    {}
func (*QueryFeeMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{9}
}
func (m *QueryFeeMetricsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFeeMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFeeMetricsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFeeMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFeeMetricsResponse.Merge(m, src)
}
func (m *QueryFeeMetricsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFeeMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFeeMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFeeMetricsResponse proto.InternalMessageInfo

func (m *QueryFeeMetricsResponse) GetMetrics() FeeMetrics {
	if m != nil {
		return m.Metrics
	}
	return FeeMetrics{}
}

// QueryContributorFeeStatsRequest is the request type for the Query/ContributorFeeStats RPC method.
type QueryContributorFeeStatsRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryContributorFeeStatsRequest) Reset()         { *m = QueryContributorFeeStatsRequest{} }
func (m *QueryContributorFeeStatsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryContributorFeeStatsRequest) ProtoMessage()    {}
func (*QueryContributorFeeStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{10}
}
func (m *QueryContributorFeeStatsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContributorFeeStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContributorFeeStatsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContributorFeeStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContributorFeeStatsRequest.Merge(m, src)
}
func (m *QueryContributorFeeStatsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryContributorFeeStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContributorFeeStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContributorFeeStatsRequest proto.InternalMessageInfo

func (m *QueryContributorFeeStatsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

// QueryContributorFeeStatsResponse is the response type for the Query/ContributorFeeStats RPC method.
type QueryContributorFeeStatsResponse struct {
	Stats ContributorFeeStats `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats"`
}

func (m *QueryContributorFeeStatsResponse) Reset()         { *m = QueryContributorFeeStatsResponse{} }
func (m *QueryContributorFeeStatsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryContributorFeeStatsResponse) ProtoMessage()    {}
func (*QueryContributorFeeStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_447ecebb6b2e58d5, []int{11}
}
func (m *QueryContributorFeeStatsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContributorFeeStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContributorFeeStatsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContributorFeeStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContributorFeeStatsResponse.Merge(m, src)
}
func (m *QueryContributorFeeStatsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryContributorFeeStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContributorFeeStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContributorFeeStatsResponse proto.InternalMessageInfo

func (m *QueryContributorFeeStatsResponse) GetStats() ContributorFeeStats {
	if m != nil {
		return m.Stats
	}
	return ContributorFeeStats{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "pos.poc.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "pos.poc.v1.QueryParamsResponse")
	proto.RegisterType((*QueryContributionRequest)(nil), "pos.poc.v1.QueryContributionRequest")
	proto.RegisterType((*QueryContributionResponse)(nil), "pos.poc.v1.QueryContributionResponse")
	proto.RegisterType((*QueryContributionsRequest)(nil), "pos.poc.v1.QueryContributionsRequest")
	proto.RegisterType((*QueryContributionsResponse)(nil), "pos.poc.v1.QueryContributionsResponse")
	proto.RegisterType((*QueryCreditsRequest)(nil), "pos.poc.v1.QueryCreditsRequest")
	proto.RegisterType((*QueryCreditsResponse)(nil), "pos.poc.v1.QueryCreditsResponse")
	proto.RegisterType((*QueryFeeMetricsRequest)(nil), "pos.poc.v1.QueryFeeMetricsRequest")
	proto.RegisterType((*QueryFeeMetricsResponse)(nil), "pos.poc.v1.QueryFeeMetricsResponse")
	proto.RegisterType((*QueryContributorFeeStatsRequest)(nil), "pos.poc.v1.QueryContributorFeeStatsRequest")
	proto.RegisterType((*QueryContributorFeeStatsResponse)(nil), "pos.poc.v1.QueryContributorFeeStatsResponse")
}

func init() { proto.RegisterFile("pos/poc/v1/query.proto", fileDescriptor_447ecebb6b2e58d5) }

var fileDescriptor_447ecebb6b2e58d5 = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x4f, 0x4f, 0xdb, 0x48,
	0x14, 0x8f, 0x43, 0xfe, 0x2c, 0x0f, 0xd8, 0xd5, 0x3e, 0x22, 0x30, 0x5e, 0x48, 0xb2, 0xde, 0x85,
	0x52, 0x68, 0x3d, 0x0a, 0xa8, 0xbd, 0x70, 0x0b, 0x15, 0xbd, 0xb4, 0x12, 0xa4, 0xb7, 0x5e, 0x22,
	0x27, 0x19, 0x22, 0x4b, 0x4d, 0xc6, 0xd8, 0x26, 0x2a, 0x42, 0x1c, 0xca, 0xb9, 0x87, 0x4a, 0xfd,
	0x0c, 0x95, 0x2a, 0xf5, 0xd2, 0x5b, 0xbf, 0x02, 0x47, 0xa4, 0x5e, 0x7a, 0xaa, 0x2a, 0xa8, 0xd4,
	0xaf, 0x51, 0x79, 0xe6, 0x25, 0xb1, 0x65, 0x07, 0xb8, 0x44, 0x9e, 0x79, 0xbf, 0xf7, 0x7e, 0xbf,
	0xf7, 0x6f, 0x02, 0x0b, 0xae, 0xf0, 0x99, 0x2b, 0xda, 0x6c, 0x50, 0x63, 0x47, 0xc7, 0xdc, 0x3b,
	0xb1, 0x5c, 0x4f, 0x04, 0x02, 0xc1, 0x15, 0xbe, 0xe5, 0x8a, 0xb6, 0x35, 0xa8, 0x19, 0x7f, 0xdb,
	0x3d, 0xa7, 0x2f, 0x98, 0xfc, 0x55, 0x66, 0xa3, 0xd4, 0x15, 0x5d, 0x21, 0x3f, 0x59, 0xf8, 0x45,
	0xb7, 0xcb, 0x5d, 0x21, 0xba, 0xaf, 0x38, 0xb3, 0x5d, 0x87, 0xd9, 0xfd, 0xbe, 0x08, 0xec, 0xc0,
	0x11, 0x7d, 0x9f, 0xac, 0x1b, 0x6d, 0xe1, 0xf7, 0x84, 0xcf, 0x5a, 0xb6, 0xcf, 0x15, 0x17, 0x1b,
	0xd4, 0x5a, 0x3c, 0xb0, 0x6b, 0xcc, 0xb5, 0xbb, 0x4e, 0x5f, 0x82, 0x09, 0xbb, 0x18, 0x91, 0xe5,
	0xda, 0x9e, 0xdd, 0x1b, 0x06, 0x59, 0x89, 0x18, 0xda, 0xa2, 0x1f, 0x78, 0x4e, 0xeb, 0x38, 0xe2,
	0xb7, 0x1c, 0x31, 0x1f, 0x72, 0xde, 0xec, 0xf1, 0xc0, 0x73, 0xda, 0xe4, 0x6c, 0x96, 0x00, 0x0f,
	0x42, 0xde, 0x7d, 0x19, 0xb1, 0xc1, 0x8f, 0x8e, 0xb9, 0x1f, 0x98, 0xcf, 0x60, 0x3e, 0x76, 0xeb,
	0xbb, 0xa2, 0xef, 0x73, 0x7c, 0x04, 0x05, 0xc5, 0xac, 0x6b, 0x55, 0x6d, 0x7d, 0x66, 0x0b, 0xad,
	0x71, 0x49, 0x2c, 0x85, 0xad, 0x4f, 0x5f, 0x7c, 0xaf, 0x64, 0x3e, 0xfe, 0xfa, 0xbc, 0xa1, 0x35,
	0x08, 0x6c, 0x6e, 0x80, 0x2e, 0xa3, 0xed, 0x46, 0xc4, 0x11, 0x13, 0xfe, 0x09, 0x59, 0xa7, 0x23,
	0xc3, 0xe5, 0x1a, 0x59, 0xa7, 0x63, 0x36, 0x61, 0x29, 0x05, 0x4b, 0xfc, 0x75, 0x98, 0x8d, 0x26,
	0x48, 0x2a, 0xf4, 0xa8, 0x8a, 0xa8, 0x5f, 0x3d, 0x17, 0x6a, 0x69, 0xc4, 0x7c, 0xcc, 0x2f, 0x5a,
	0x0a, 0xc3, 0x30, 0x71, 0xac, 0xc2, 0xcc, 0x08, 0x2d, 0x3c, 0x49, 0x30, 0xdd, 0x88, 0x5e, 0x61,
	0x09, 0xf2, 0xed, 0xe0, 0xc4, 0xe5, 0x7a, 0x56, 0xda, 0xd4, 0x01, 0x0d, 0xf8, 0x63, 0xc0, 0x3d,
	0xe7, 0xd0, 0xe1, 0x1d, 0x7d, 0xaa, 0xaa, 0xad, 0xe7, 0x1b, 0xa3, 0x33, 0xee, 0x01, 0x8c, 0x9b,
	0xa9, 0xe7, 0xa4, 0xe6, 0x35, 0x4b, 0x75, 0xde, 0x0a, 0x3b, 0x6f, 0xa9, 0x29, 0xa3, 0xce, 0x5b,
	0xfb, 0x76, 0x97, 0x93, 0x9e, 0x46, 0xc4, 0xd3, 0xfc, 0xa4, 0x81, 0x91, 0xa6, 0x9c, 0x8a, 0xf3,
	0x04, 0xe6, 0xa2, 0x89, 0x86, 0x3d, 0x9a, 0xba, 0x43, 0x75, 0xe2, 0x4e, 0xf8, 0x34, 0x26, 0x36,
	0x2b, 0xc5, 0xde, 0xbb, 0x55, 0xac, 0x92, 0x10, 0x53, 0xcb, 0x68, 0x84, 0x76, 0x3d, 0xde, 0x71,
	0x82, 0x51, 0x81, 0x75, 0x28, 0xda, 0x9d, 0x8e, 0xc7, 0x7d, 0x9f, 0x8a, 0x3b, 0x3c, 0x9a, 0x4d,
	0x28, 0xc5, 0x1d, 0x28, 0xaf, 0x6d, 0x28, 0xb6, 0xd5, 0x15, 0xf5, 0x7b, 0x3e, 0x96, 0x91, 0x32,
	0x51, 0x32, 0x43, 0x24, 0x22, 0xe4, 0x02, 0x87, 0x7b, 0xd4, 0x24, 0xf9, 0x6d, 0xea, 0xb0, 0x20,
	0x09, 0xf6, 0x38, 0x7f, 0xae, 0x76, 0x60, 0x38, 0xee, 0x07, 0xb0, 0x98, 0xb0, 0x10, 0xfb, 0x63,
	0x28, 0xd2, 0xc2, 0x10, 0xfb, 0x42, 0x94, 0x7d, 0xec, 0x30, 0x14, 0x40, 0x60, 0x73, 0x07, 0x2a,
	0xf1, 0x5e, 0x09, 0x6f, 0x8f, 0xf3, 0x17, 0x81, 0x7d, 0xb7, 0x52, 0x54, 0x27, 0x3b, 0x93, 0xb0,
	0x1d, 0xc8, 0xfb, 0xe1, 0x05, 0xc9, 0xaa, 0xa4, 0xb6, 0x79, 0xec, 0x47, 0xfa, 0x94, 0xcf, 0xd6,
	0xdb, 0x02, 0xe4, 0x25, 0x03, 0x72, 0x28, 0xa8, 0xc5, 0xc5, 0x72, 0x34, 0x42, 0xf2, 0x4d, 0x30,
	0x2a, 0x13, 0xed, 0x4a, 0x91, 0x69, 0x9c, 0x7f, 0xfd, 0xf9, 0x3e, 0x5b, 0x42, 0x64, 0x89, 0x97,
	0x0a, 0xcf, 0x35, 0x98, 0x8d, 0x0e, 0x1f, 0xfe, 0x9f, 0x88, 0x96, 0xf2, 0x3a, 0x18, 0xab, 0xb7,
	0xa0, 0x88, 0x79, 0x55, 0x32, 0x57, 0x70, 0x85, 0x4d, 0x78, 0x0a, 0xd9, 0xa9, 0xd3, 0x39, 0xc3,
	0x37, 0x1a, 0xcc, 0xc5, 0x76, 0x07, 0x6f, 0x8e, 0x3f, 0x4a, 0x7d, 0xed, 0x36, 0x18, 0xe9, 0xf8,
	0x57, 0xea, 0xf8, 0x07, 0x97, 0x26, 0xe9, 0xf0, 0xd1, 0x87, 0x22, 0x8d, 0x2c, 0x26, 0x0b, 0x1a,
	0xdf, 0x15, 0xa3, 0x3a, 0x19, 0x70, 0x63, 0xe2, 0x0a, 0xc4, 0x4e, 0x69, 0x9c, 0xce, 0x70, 0x00,
	0x30, 0x9e, 0x54, 0x34, 0x13, 0x61, 0x13, 0x1b, 0x61, 0xfc, 0x77, 0x23, 0x86, 0xd8, 0x2b, 0x92,
	0x7d, 0x09, 0x17, 0x59, 0xfa, 0x5f, 0x0c, 0x7e, 0xd0, 0x60, 0x3e, 0x65, 0x16, 0x71, 0x73, 0x72,
	0x3d, 0x13, 0x6b, 0x62, 0x3c, 0xb8, 0x1b, 0x98, 0x34, 0x6d, 0x4b, 0x4d, 0x0f, 0x71, 0x33, 0xb5,
	0x05, 0xc2, 0x6b, 0x86, 0xfa, 0xe4, 0x12, 0x8c, 0xeb, 0x53, 0xbf, 0x7f, 0x71, 0x55, 0xd6, 0x2e,
	0xaf, 0xca, 0xda, 0x8f, 0xab, 0xb2, 0xf6, 0xee, 0xba, 0x9c, 0xb9, 0xbc, 0x2e, 0x67, 0xbe, 0x5d,
	0x97, 0x33, 0x2f, 0xff, 0x0a, 0xa3, 0xbc, 0x96, 0x71, 0xc2, 0x77, 0xde, 0x6f, 0x15, 0xe4, 0xdf,
	0xe6, 0xf6, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x53, 0xc2, 0x91, 0x0d, 0x25, 0x08, 0x00, 0x00,
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryContributionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContributionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContributionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryContributionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContributionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContributionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Contribution.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryContributionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContributionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContributionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Verified != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Verified))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Ctype) > 0 {
		i -= len(m.Ctype)
		copy(dAtA[i:], m.Ctype)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Ctype)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Contributor) > 0 {
		i -= len(m.Contributor)
		copy(dAtA[i:], m.Contributor)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Contributor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryContributionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContributionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContributionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Contributions) > 0 {
		for iNdEx := len(m.Contributions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Contributions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryCreditsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCreditsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCreditsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCreditsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCreditsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCreditsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tier) > 0 {
		i -= len(m.Tier)
		copy(dAtA[i:], m.Tier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Tier)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Credits.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryFeeMetricsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFeeMetricsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFeeMetricsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryFeeMetricsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFeeMetricsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFeeMetricsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Metrics.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryContributorFeeStatsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContributorFeeStatsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContributorFeeStatsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryContributorFeeStatsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContributorFeeStatsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContributorFeeStatsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Stats.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryContributionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryContributionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Contribution.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryContributionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Contributor)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Ctype)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Verified != 0 {
		n += 1 + sovQuery(uint64(m.Verified))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryContributionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Contributions) > 0 {
		for _, e := range m.Contributions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCreditsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCreditsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Credits.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = len(m.Tier)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFeeMetricsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryFeeMetricsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Metrics.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryContributorFeeStatsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryContributorFeeStatsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Stats.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContributionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContributionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContributionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContributionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContributionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContributionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Contribution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContributionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContributionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContributionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contributor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contributor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ctype", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ctype = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verified", wireType)
			}
			m.Verified = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Verified |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContributionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContributionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContributionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contributions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contributions = append(m.Contributions, Contribution{})
			if err := m.Contributions[len(m.Contributions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCreditsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCreditsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCreditsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCreditsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCreditsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCreditsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Credits.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFeeMetricsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFeeMetricsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFeeMetricsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFeeMetricsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFeeMetricsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFeeMetricsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metrics", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Metrics.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContributorFeeStatsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContributorFeeStatsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContributorFeeStatsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContributorFeeStatsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContributorFeeStatsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContributorFeeStatsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Stats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
