// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the module parameters
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Operation returns a specific operation by ID
	Operation(ctx context.Context, in *QueryOperationRequest, opts ...grpc.CallOption) (*QueryOperationResponse, error)
	// Operations returns all operations with optional status filter
	Operations(ctx context.Context, in *QueryOperationsRequest, opts ...grpc.CallOption) (*QueryOperationsResponse, error)
	// QueuedOperations returns all operations in QUEUED status
	QueuedOperations(ctx context.Context, in *QueryQueuedOperationsRequest, opts ...grpc.CallOption) (*QueryQueuedOperationsResponse, error)
	// ExecutableOperations returns operations ready for execution
	ExecutableOperations(ctx context.Context, in *QueryExecutableOperationsRequest, opts ...grpc.CallOption) (*QueryExecutableOperationsResponse, error)
	// OperationByHash returns an operation by its hash
	OperationByHash(ctx context.Context, in *QueryOperationByHashRequest, opts ...grpc.CallOption) (*QueryOperationByHashResponse, error)
	// OperationsByProposal returns all operations for a governance proposal
	OperationsByProposal(ctx context.Context, in *QueryOperationsByProposalRequest, opts ...grpc.CallOption) (*QueryOperationsByProposalResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Operation(ctx context.Context, in *QueryOperationRequest, opts ...grpc.CallOption) (*QueryOperationResponse, error) {
	out := new(QueryOperationResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Query/Operation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Operations(ctx context.Context, in *QueryOperationsRequest, opts ...grpc.CallOption) (*QueryOperationsResponse, error) {
	out := new(QueryOperationsResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Query/Operations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueuedOperations(ctx context.Context, in *QueryQueuedOperationsRequest, opts ...grpc.CallOption) (*QueryQueuedOperationsResponse, error) {
	out := new(QueryQueuedOperationsResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Query/QueuedOperations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ExecutableOperations(ctx context.Context, in *QueryExecutableOperationsRequest, opts ...grpc.CallOption) (*QueryExecutableOperationsResponse, error) {
	out := new(QueryExecutableOperationsResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Query/ExecutableOperations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OperationByHash(ctx context.Context, in *QueryOperationByHashRequest, opts ...grpc.CallOption) (*QueryOperationByHashResponse, error) {
	out := new(QueryOperationByHashResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Query/OperationByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OperationsByProposal(ctx context.Context, in *QueryOperationsByProposalRequest, opts ...grpc.CallOption) (*QueryOperationsByProposalResponse, error) {
	out := new(QueryOperationsByProposalResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Query/OperationsByProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Params returns the module parameters
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Operation returns a specific operation by ID
	Operation(context.Context, *QueryOperationRequest) (*QueryOperationResponse, error)
	// Operations returns all operations with optional status filter
	Operations(context.Context, *QueryOperationsRequest) (*QueryOperationsResponse, error)
	// QueuedOperations returns all operations in QUEUED status
	QueuedOperations(context.Context, *QueryQueuedOperationsRequest) (*QueryQueuedOperationsResponse, error)
	// ExecutableOperations returns operations ready for execution
	ExecutableOperations(context.Context, *QueryExecutableOperationsRequest) (*QueryExecutableOperationsResponse, error)
	// OperationByHash returns an operation by its hash
	OperationByHash(context.Context, *QueryOperationByHashRequest) (*QueryOperationByHashResponse, error)
	// OperationsByProposal returns all operations for a governance proposal
	OperationsByProposal(context.Context, *QueryOperationsByProposalRequest) (*QueryOperationsByProposalResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Operation(context.Context, *QueryOperationRequest) (*QueryOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Operation not implemented")
}
func (UnimplementedQueryServer) Operations(context.Context, *QueryOperationsRequest) (*QueryOperationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Operations not implemented")
}
func (UnimplementedQueryServer) QueuedOperations(context.Context, *QueryQueuedOperationsRequest) (*QueryQueuedOperationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueuedOperations not implemented")
}
func (UnimplementedQueryServer) ExecutableOperations(context.Context, *QueryExecutableOperationsRequest) (*QueryExecutableOperationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutableOperations not implemented")
}
func (UnimplementedQueryServer) OperationByHash(context.Context, *QueryOperationByHashRequest) (*QueryOperationByHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OperationByHash not implemented")
}
func (UnimplementedQueryServer) OperationsByProposal(context.Context, *QueryOperationsByProposalRequest) (*QueryOperationsByProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OperationsByProposal not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Operation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Operation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Query/Operation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Operation(ctx, req.(*QueryOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Operations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Operations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Query/Operations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Operations(ctx, req.(*QueryOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueuedOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryQueuedOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueuedOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Query/QueuedOperations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueuedOperations(ctx, req.(*QueryQueuedOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ExecutableOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryExecutableOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ExecutableOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Query/ExecutableOperations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ExecutableOperations(ctx, req.(*QueryExecutableOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OperationByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOperationByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OperationByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Query/OperationByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OperationByHash(ctx, req.(*QueryOperationByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OperationsByProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOperationsByProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OperationsByProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Query/OperationsByProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OperationsByProposal(ctx, req.(*QueryOperationsByProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pos.timelock.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Operation",
			Handler:    _Query_Operation_Handler,
		},
		{
			MethodName: "Operations",
			Handler:    _Query_Operations_Handler,
		},
		{
			MethodName: "QueuedOperations",
			Handler:    _Query_QueuedOperations_Handler,
		},
		{
			MethodName: "ExecutableOperations",
			Handler:    _Query_ExecutableOperations_Handler,
		},
		{
			MethodName: "OperationByHash",
			Handler:    _Query_OperationByHash_Handler,
		},
		{
			MethodName: "OperationsByProposal",
			Handler:    _Query_OperationsByProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pos/timelock/v1/query.proto",
}
