// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// ExecuteOperation executes a queued operation after the delay has passed
	ExecuteOperation(ctx context.Context, in *MsgExecuteOperation, opts ...grpc.CallOption) (*MsgExecuteOperationResponse, error)
	// CancelOperation cancels a queued operation (guardian only)
	CancelOperation(ctx context.Context, in *MsgCancelOperation, opts ...grpc.CallOption) (*MsgCancelOperationResponse, error)
	// EmergencyExecute executes an operation with reduced delay (guardian only)
	EmergencyExecute(ctx context.Context, in *MsgEmergencyExecute, opts ...grpc.CallOption) (*MsgEmergencyExecuteResponse, error)
	// UpdateParams updates the module parameters (governance only)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// UpdateGuardian updates the guardian address (governance only)
	UpdateGuardian(ctx context.Context, in *MsgUpdateGuardian, opts ...grpc.CallOption) (*MsgUpdateGuardianResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ExecuteOperation(ctx context.Context, in *MsgExecuteOperation, opts ...grpc.CallOption) (*MsgExecuteOperationResponse, error) {
	out := new(MsgExecuteOperationResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Msg/ExecuteOperation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelOperation(ctx context.Context, in *MsgCancelOperation, opts ...grpc.CallOption) (*MsgCancelOperationResponse, error) {
	out := new(MsgCancelOperationResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Msg/CancelOperation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) EmergencyExecute(ctx context.Context, in *MsgEmergencyExecute, opts ...grpc.CallOption) (*MsgEmergencyExecuteResponse, error) {
	out := new(MsgEmergencyExecuteResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Msg/EmergencyExecute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateGuardian(ctx context.Context, in *MsgUpdateGuardian, opts ...grpc.CallOption) (*MsgUpdateGuardianResponse, error) {
	out := new(MsgUpdateGuardianResponse)
	err := c.cc.Invoke(ctx, "/pos.timelock.v1.Msg/UpdateGuardian", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// ExecuteOperation executes a queued operation after the delay has passed
	ExecuteOperation(context.Context, *MsgExecuteOperation) (*MsgExecuteOperationResponse, error)
	// CancelOperation cancels a queued operation (guardian only)
	CancelOperation(context.Context, *MsgCancelOperation) (*MsgCancelOperationResponse, error)
	// EmergencyExecute executes an operation with reduced delay (guardian only)
	EmergencyExecute(context.Context, *MsgEmergencyExecute) (*MsgEmergencyExecuteResponse, error)
	// UpdateParams updates the module parameters (governance only)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// UpdateGuardian updates the guardian address (governance only)
	UpdateGuardian(context.Context, *MsgUpdateGuardian) (*MsgUpdateGuardianResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) ExecuteOperation(context.Context, *MsgExecuteOperation) (*MsgExecuteOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteOperation not implemented")
}
func (UnimplementedMsgServer) CancelOperation(context.Context, *MsgCancelOperation) (*MsgCancelOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOperation not implemented")
}
func (UnimplementedMsgServer) EmergencyExecute(context.Context, *MsgEmergencyExecute) (*MsgEmergencyExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmergencyExecute not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) UpdateGuardian(context.Context, *MsgUpdateGuardian) (*MsgUpdateGuardianResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGuardian not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_ExecuteOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExecuteOperation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExecuteOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Msg/ExecuteOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExecuteOperation(ctx, req.(*MsgExecuteOperation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelOperation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Msg/CancelOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelOperation(ctx, req.(*MsgCancelOperation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_EmergencyExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEmergencyExecute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EmergencyExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Msg/EmergencyExecute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EmergencyExecute(ctx, req.(*MsgEmergencyExecute))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateGuardian_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateGuardian)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateGuardian(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.timelock.v1.Msg/UpdateGuardian",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateGuardian(ctx, req.(*MsgUpdateGuardian))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pos.timelock.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteOperation",
			Handler:    _Msg_ExecuteOperation_Handler,
		},
		{
			MethodName: "CancelOperation",
			Handler:    _Msg_CancelOperation_Handler,
		},
		{
			MethodName: "EmergencyExecute",
			Handler:    _Msg_EmergencyExecute_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "UpdateGuardian",
			Handler:    _Msg_UpdateGuardian_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pos/timelock/v1/tx.proto",
}
