// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the parameters of the feemarket module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// BaseFee queries the current EIP-1559 base fee.
	BaseFee(ctx context.Context, in *QueryBaseFeeRequest, opts ...grpc.CallOption) (*QueryBaseFeeResponse, error)
	// BlockUtilization queries the current block utilization.
	BlockUtilization(ctx context.Context, in *QueryBlockUtilizationRequest, opts ...grpc.CallOption) (*QueryBlockUtilizationResponse, error)
	// BurnTier queries the current burn tier based on utilization.
	BurnTier(ctx context.Context, in *QueryBurnTierRequest, opts ...grpc.CallOption) (*QueryBurnTierResponse, error)
	// FeeStats queries cumulative fee statistics.
	FeeStats(ctx context.Context, in *QueryFeeStatsRequest, opts ...grpc.CallOption) (*QueryFeeStatsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/pos.feemarket.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BaseFee(ctx context.Context, in *QueryBaseFeeRequest, opts ...grpc.CallOption) (*QueryBaseFeeResponse, error) {
	out := new(QueryBaseFeeResponse)
	err := c.cc.Invoke(ctx, "/pos.feemarket.v1.Query/BaseFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BlockUtilization(ctx context.Context, in *QueryBlockUtilizationRequest, opts ...grpc.CallOption) (*QueryBlockUtilizationResponse, error) {
	out := new(QueryBlockUtilizationResponse)
	err := c.cc.Invoke(ctx, "/pos.feemarket.v1.Query/BlockUtilization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BurnTier(ctx context.Context, in *QueryBurnTierRequest, opts ...grpc.CallOption) (*QueryBurnTierResponse, error) {
	out := new(QueryBurnTierResponse)
	err := c.cc.Invoke(ctx, "/pos.feemarket.v1.Query/BurnTier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FeeStats(ctx context.Context, in *QueryFeeStatsRequest, opts ...grpc.CallOption) (*QueryFeeStatsResponse, error) {
	out := new(QueryFeeStatsResponse)
	err := c.cc.Invoke(ctx, "/pos.feemarket.v1.Query/FeeStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Params queries the parameters of the feemarket module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// BaseFee queries the current EIP-1559 base fee.
	BaseFee(context.Context, *QueryBaseFeeRequest) (*QueryBaseFeeResponse, error)
	// BlockUtilization queries the current block utilization.
	BlockUtilization(context.Context, *QueryBlockUtilizationRequest) (*QueryBlockUtilizationResponse, error)
	// BurnTier queries the current burn tier based on utilization.
	BurnTier(context.Context, *QueryBurnTierRequest) (*QueryBurnTierResponse, error)
	// FeeStats queries cumulative fee statistics.
	FeeStats(context.Context, *QueryFeeStatsRequest) (*QueryFeeStatsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) BaseFee(context.Context, *QueryBaseFeeRequest) (*QueryBaseFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BaseFee not implemented")
}
func (UnimplementedQueryServer) BlockUtilization(context.Context, *QueryBlockUtilizationRequest) (*QueryBlockUtilizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockUtilization not implemented")
}
func (UnimplementedQueryServer) BurnTier(context.Context, *QueryBurnTierRequest) (*QueryBurnTierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnTier not implemented")
}
func (UnimplementedQueryServer) FeeStats(context.Context, *QueryFeeStatsRequest) (*QueryFeeStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeeStats not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.feemarket.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BaseFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBaseFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BaseFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.feemarket.v1.Query/BaseFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BaseFee(ctx, req.(*QueryBaseFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BlockUtilization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBlockUtilizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BlockUtilization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.feemarket.v1.Query/BlockUtilization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BlockUtilization(ctx, req.(*QueryBlockUtilizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BurnTier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBurnTierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BurnTier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.feemarket.v1.Query/BurnTier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BurnTier(ctx, req.(*QueryBurnTierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FeeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFeeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FeeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.feemarket.v1.Query/FeeStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FeeStats(ctx, req.(*QueryFeeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pos.feemarket.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "BaseFee",
			Handler:    _Query_BaseFee_Handler,
		},
		{
			MethodName: "BlockUtilization",
			Handler:    _Query_BlockUtilization_Handler,
		},
		{
			MethodName: "BurnTier",
			Handler:    _Query_BurnTier_Handler,
		},
		{
			MethodName: "FeeStats",
			Handler:    _Query_FeeStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pos/feemarket/v1/query.proto",
}
