// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pos/poc/v1/fee_metrics.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FeeMetrics tracks cumulative fee burn statistics for the PoC module
// This provides transparency and audit trail for fee collection and burning
type FeeMetrics struct {
	// total_fees_collected is the cumulative amount of submission fees collected
	TotalFeesCollected types.Coins `protobuf:"bytes,1,rep,name=total_fees_collected,json=totalFeesCollected,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_fees_collected"`
	// total_burned is the cumulative amount burned from submission fees
	TotalBurned types.Coins `protobuf:"bytes,2,rep,name=total_burned,json=totalBurned,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_burned"`
	// total_reward_redirect is the cumulative amount sent to PoC reward pool
	TotalRewardRedirect types.Coins `protobuf:"bytes,3,rep,name=total_reward_redirect,json=totalRewardRedirect,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_reward_redirect"`
	// last_updated_height is the block height when metrics were last updated
	LastUpdatedHeight int64 `protobuf:"varint,4,opt,name=last_updated_height,json=lastUpdatedHeight,proto3" json:"last_updated_height,omitempty"`
}

func (m *FeeMetrics) Reset()         { *m = FeeMetrics{} }
func (m *FeeMetrics) String() string { return proto.CompactTextString(m) }
func (*FeeMetrics) ProtoMessage()    {}
func (*FeeMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_fee_metrics, []int{0}
}

// ContributorFeeStats tracks per-contributor fee statistics
// This enables analytics on contributor behavior and fee rebate mechanisms
type ContributorFeeStats struct {
	// address is the contributor's address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// total_fees_paid is the total fees paid by this contributor
	TotalFeesPaid types.Coins `protobuf:"bytes,2,rep,name=total_fees_paid,json=totalFeesPaid,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_fees_paid"`
	// total_burned is the total amount burned from this contributor's fees
	TotalBurned types.Coins `protobuf:"bytes,3,rep,name=total_burned,json=totalBurned,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_burned"`
	// submission_count is the total number of submissions by this contributor
	SubmissionCount uint64 `protobuf:"varint,4,opt,name=submission_count,json=submissionCount,proto3" json:"submission_count,omitempty"`
	// first_submission_height is the block height of first submission
	FirstSubmissionHeight int64 `protobuf:"varint,5,opt,name=first_submission_height,json=firstSubmissionHeight,proto3" json:"first_submission_height,omitempty"`
	// last_submission_height is the block height of most recent submission
	LastSubmissionHeight int64 `protobuf:"varint,6,opt,name=last_submission_height,json=lastSubmissionHeight,proto3" json:"last_submission_height,omitempty"`
}

func (m *ContributorFeeStats) Reset()         { *m = ContributorFeeStats{} }
func (m *ContributorFeeStats) String() string { return proto.CompactTextString(m) }
func (*ContributorFeeStats) ProtoMessage()    {}
func (*ContributorFeeStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_fee_metrics, []int{1}
}

func init() {
	proto.RegisterType((*FeeMetrics)(nil), "pos.poc.v1.FeeMetrics")
	proto.RegisterType((*ContributorFeeStats)(nil), "pos.poc.v1.ContributorFeeStats")
}

func (m *FeeMetrics) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeMetrics) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeMetrics) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastUpdatedHeight != 0 {
		i = encodeVarintFeeMetrics(dAtA, i, uint64(m.LastUpdatedHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TotalRewardRedirect) > 0 {
		for iNdEx := len(m.TotalRewardRedirect) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalRewardRedirect[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeeMetrics(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.TotalBurned) > 0 {
		for iNdEx := len(m.TotalBurned) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalBurned[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeeMetrics(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.TotalFeesCollected) > 0 {
		for iNdEx := len(m.TotalFeesCollected) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalFeesCollected[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeeMetrics(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ContributorFeeStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContributorFeeStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContributorFeeStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastSubmissionHeight != 0 {
		i = encodeVarintFeeMetrics(dAtA, i, uint64(m.LastSubmissionHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.FirstSubmissionHeight != 0 {
		i = encodeVarintFeeMetrics(dAtA, i, uint64(m.FirstSubmissionHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.SubmissionCount != 0 {
		i = encodeVarintFeeMetrics(dAtA, i, uint64(m.SubmissionCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TotalBurned) > 0 {
		for iNdEx := len(m.TotalBurned) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalBurned[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeeMetrics(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.TotalFeesPaid) > 0 {
		for iNdEx := len(m.TotalFeesPaid) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalFeesPaid[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeeMetrics(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintFeeMetrics(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFeeMetrics(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeeMetrics(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeMetrics) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TotalFeesCollected) > 0 {
		for _, e := range m.TotalFeesCollected {
			l = e.Size()
			n += 1 + l + sovFeeMetrics(uint64(l))
		}
	}
	if len(m.TotalBurned) > 0 {
		for _, e := range m.TotalBurned {
			l = e.Size()
			n += 1 + l + sovFeeMetrics(uint64(l))
		}
	}
	if len(m.TotalRewardRedirect) > 0 {
		for _, e := range m.TotalRewardRedirect {
			l = e.Size()
			n += 1 + l + sovFeeMetrics(uint64(l))
		}
	}
	if m.LastUpdatedHeight != 0 {
		n += 1 + sovFeeMetrics(uint64(m.LastUpdatedHeight))
	}
	return n
}

func (m *ContributorFeeStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovFeeMetrics(uint64(l))
	}
	if len(m.TotalFeesPaid) > 0 {
		for _, e := range m.TotalFeesPaid {
			l = e.Size()
			n += 1 + l + sovFeeMetrics(uint64(l))
		}
	}
	if len(m.TotalBurned) > 0 {
		for _, e := range m.TotalBurned {
			l = e.Size()
			n += 1 + l + sovFeeMetrics(uint64(l))
		}
	}
	if m.SubmissionCount != 0 {
		n += 1 + sovFeeMetrics(uint64(m.SubmissionCount))
	}
	if m.FirstSubmissionHeight != 0 {
		n += 1 + sovFeeMetrics(uint64(m.FirstSubmissionHeight))
	}
	if m.LastSubmissionHeight != 0 {
		n += 1 + sovFeeMetrics(uint64(m.LastSubmissionHeight))
	}
	return n
}

func sovFeeMetrics(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}

func (m *FeeMetrics) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeeMetrics
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeMetrics: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeMetrics: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalFeesCollected", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalFeesCollected = append(m.TotalFeesCollected, types.Coin{})
			if err := m.TotalFeesCollected[len(m.TotalFeesCollected)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBurned", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalBurned = append(m.TotalBurned, types.Coin{})
			if err := m.TotalBurned[len(m.TotalBurned)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRewardRedirect", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
				return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalRewardRedirect = append(m.TotalRewardRedirect, types.Coin{})
			if err := m.TotalRewardRedirect[len(m.TotalRewardRedirect)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdatedHeight", wireType)
			}
			m.LastUpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeeMetrics(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *ContributorFeeStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeeMetrics
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContributorFeeStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContributorFeeStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalFeesPaid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalFeesPaid = append(m.TotalFeesPaid, types.Coin{})
			if err := m.TotalFeesPaid[len(m.TotalFeesPaid)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBurned", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalBurned = append(m.TotalBurned, types.Coin{})
			if err := m.TotalBurned[len(m.TotalBurned)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmissionCount", wireType)
			}
			m.SubmissionCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubmissionCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstSubmissionHeight", wireType)
			}
			m.FirstSubmissionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FirstSubmissionHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSubmissionHeight", wireType)
			}
			m.LastSubmissionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastSubmissionHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeeMetrics(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeeMetrics
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func skipFeeMetrics(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeeMetrics
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeeMetrics
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeeMetrics
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeeMetrics
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeeMetrics
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeeMetrics        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeeMetrics          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeeMetrics = fmt.Errorf("proto: unexpected end of group")
)

var fileDescriptor_fee_metrics = []byte{
	// Fee metrics proto descriptor (placeholder)
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0xc8, 0x2f, 0xd6,
}
