#!/bin/bash
# Remove redundant documentation files

# Files to DELETE (redundant/outdated)
rm -f UBUNTU_QUICK_FIX.md
rm -f START_HERE.md
rm -f UBUNTU_SETUP.md
rm -f START_HERE_NOW.md
rm -f SIMPLE_START.md
rm -f QUICK_START.md
rm -f QUICK_START_EXISTING_CHAIN.md
rm -f START_CHAIN_GUIDE.md
rm -f FIX_MIN_GAS_PRICE_LINUX.md
rm -f DEPLOYMENT_WORKFLOW.md
rm -f PRODUCTION_DEPLOYMENT_GUIDE.md
rm -f TESTNET_DEPLOYMENT_GUIDE.md
rm -f NEXT_SESSION_INSTRUCTIONS.md
rm -f COMPLETE_SOLUTION_SUMMARY.md
rm -f IMPLEMENTATION_COMPLETE_SUMMARY.md
rm -f ADAPTIVE_FEE_MARKET_V2_SESSION_SUMMARY.md
rm -f ADAPTIVE_FEE_MARKET_V2_IMPLEMENTATION_PLAN.md
rm -f ADAPTIVE_FEE_MARKET_V2_PROGRESS.md
rm -f ADAPTIVE_BURN_IMPLEMENTATION.md
rm -f ADAPTIVE_BURN_IMPLEMENTATION_STATUS.md
rm -f FEEMARKET_FIX_COMPLETE.md
rm -f FEE_BURN_IMPLEMENTATION_STATUS.md
rm -f POC_FEE_BURN_COMPLETE.md
rm -f REWARD_DENOM_FIX_COMPLETE.md
rm -f TOKENOMICS_FINAL_STATUS.md
rm -f VALIDATOR_SUCCESS_REFLECTION_ERROR.md
rm -f DOCUMENTATION_INDEX.md

echo "Cleanup complete!"
echo ""
echo "Remaining essential documentation:"
ls -1 *.md 2>/dev/null | sort
