// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a governance operation for updating the x/guard module parameters.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// ConfirmExecution confirms execution for a CRITICAL proposal requiring second confirmation
	ConfirmExecution(ctx context.Context, in *MsgConfirmExecution, opts ...grpc.CallOption) (*MsgConfirmExecutionResponse, error)
	// UpdateAIModel updates the AI model configuration (Layer 2)
	UpdateAIModel(ctx context.Context, in *MsgUpdateAIModel, opts ...grpc.CallOption) (*MsgUpdateAIModelResponse, error)
	// SubmitAdvisoryLink submits an advisory report link (Layer 3)
	SubmitAdvisoryLink(ctx context.Context, in *MsgSubmitAdvisoryLink, opts ...grpc.CallOption) (*MsgSubmitAdvisoryLinkResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/pos.guard.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ConfirmExecution(ctx context.Context, in *MsgConfirmExecution, opts ...grpc.CallOption) (*MsgConfirmExecutionResponse, error) {
	out := new(MsgConfirmExecutionResponse)
	err := c.cc.Invoke(ctx, "/pos.guard.v1.Msg/ConfirmExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateAIModel(ctx context.Context, in *MsgUpdateAIModel, opts ...grpc.CallOption) (*MsgUpdateAIModelResponse, error) {
	out := new(MsgUpdateAIModelResponse)
	err := c.cc.Invoke(ctx, "/pos.guard.v1.Msg/UpdateAIModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitAdvisoryLink(ctx context.Context, in *MsgSubmitAdvisoryLink, opts ...grpc.CallOption) (*MsgSubmitAdvisoryLinkResponse, error) {
	out := new(MsgSubmitAdvisoryLinkResponse)
	err := c.cc.Invoke(ctx, "/pos.guard.v1.Msg/SubmitAdvisoryLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a governance operation for updating the x/guard module parameters.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// ConfirmExecution confirms execution for a CRITICAL proposal requiring second confirmation
	ConfirmExecution(context.Context, *MsgConfirmExecution) (*MsgConfirmExecutionResponse, error)
	// UpdateAIModel updates the AI model configuration (Layer 2)
	UpdateAIModel(context.Context, *MsgUpdateAIModel) (*MsgUpdateAIModelResponse, error)
	// SubmitAdvisoryLink submits an advisory report link (Layer 3)
	SubmitAdvisoryLink(context.Context, *MsgSubmitAdvisoryLink) (*MsgSubmitAdvisoryLinkResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) ConfirmExecution(context.Context, *MsgConfirmExecution) (*MsgConfirmExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmExecution not implemented")
}
func (UnimplementedMsgServer) UpdateAIModel(context.Context, *MsgUpdateAIModel) (*MsgUpdateAIModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAIModel not implemented")
}
func (UnimplementedMsgServer) SubmitAdvisoryLink(context.Context, *MsgSubmitAdvisoryLink) (*MsgSubmitAdvisoryLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAdvisoryLink not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.guard.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ConfirmExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfirmExecution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConfirmExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.guard.v1.Msg/ConfirmExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConfirmExecution(ctx, req.(*MsgConfirmExecution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateAIModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateAIModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateAIModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.guard.v1.Msg/UpdateAIModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateAIModel(ctx, req.(*MsgUpdateAIModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitAdvisoryLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitAdvisoryLink)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitAdvisoryLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pos.guard.v1.Msg/SubmitAdvisoryLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitAdvisoryLink(ctx, req.(*MsgSubmitAdvisoryLink))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pos.guard.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "ConfirmExecution",
			Handler:    _Msg_ConfirmExecution_Handler,
		},
		{
			MethodName: "UpdateAIModel",
			Handler:    _Msg_UpdateAIModel_Handler,
		},
		{
			MethodName: "SubmitAdvisoryLink",
			Handler:    _Msg_SubmitAdvisoryLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pos/guard/v1/tx.proto",
}
