// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pos/timelock/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	any "github.com/cosmos/gogoproto/types/any"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OperationStatus represents the current state of a queued operation
type OperationStatus int32

const (
	// OPERATION_STATUS_UNSPECIFIED is the default value
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	// OPERATION_STATUS_QUEUED means the operation is waiting for delay to pass
	OperationStatus_OPERATION_STATUS_QUEUED OperationStatus = 1
	// OPERATION_STATUS_EXECUTED means the operation has been successfully executed
	OperationStatus_OPERATION_STATUS_EXECUTED OperationStatus = 2
	// OPERATION_STATUS_CANCELLED means the operation was cancelled by guardian
	OperationStatus_OPERATION_STATUS_CANCELLED OperationStatus = 3
	// OPERATION_STATUS_EXPIRED means the grace period has passed without execution
	OperationStatus_OPERATION_STATUS_EXPIRED OperationStatus = 4
	// OPERATION_STATUS_FAILED means execution was attempted but failed
	OperationStatus_OPERATION_STATUS_FAILED OperationStatus = 5
)

var OperationStatus_name = map[int32]string{
	0: "OPERATION_STATUS_UNSPECIFIED",
	1: "OPERATION_STATUS_QUEUED",
	2: "OPERATION_STATUS_EXECUTED",
	3: "OPERATION_STATUS_CANCELLED",
	4: "OPERATION_STATUS_EXPIRED",
	5: "OPERATION_STATUS_FAILED",
}

var OperationStatus_value = map[string]int32{
	"OPERATION_STATUS_UNSPECIFIED": 0,
	"OPERATION_STATUS_QUEUED":      1,
	"OPERATION_STATUS_EXECUTED":    2,
	"OPERATION_STATUS_CANCELLED":   3,
	"OPERATION_STATUS_EXPIRED":     4,
	"OPERATION_STATUS_FAILED":      5,
}

func (x OperationStatus) String() string {
	return proto.EnumName(OperationStatus_name, int32(x))
}

func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3397044bdb66ad0a, []int{0}
}

// Params defines the parameters for the timelock module
type Params struct {
	// min_delay_seconds is the minimum time between queueing and execution in seconds (default: 86400 = 24h)
	MinDelaySeconds uint64 `protobuf:"varint,1,opt,name=min_delay_seconds,json=minDelaySeconds,proto3" json:"min_delay_seconds,omitempty"`
	// max_delay_seconds is the maximum allowed delay in seconds (default: 1209600 = 14d)
	MaxDelaySeconds uint64 `protobuf:"varint,2,opt,name=max_delay_seconds,json=maxDelaySeconds,proto3" json:"max_delay_seconds,omitempty"`
	// grace_period_seconds is the window after min_delay during which execution is valid (default: 604800 = 7d)
	GracePeriodSeconds uint64 `protobuf:"varint,3,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	// emergency_delay_seconds is the reduced delay for emergency operations in seconds (min: 3600 = 1h)
	EmergencyDelaySeconds uint64 `protobuf:"varint,4,opt,name=emergency_delay_seconds,json=emergencyDelaySeconds,proto3" json:"emergency_delay_seconds,omitempty"`
	// guardian is the address authorized to cancel operations and emergency execute
	Guardian string `protobuf:"bytes,5,opt,name=guardian,proto3" json:"guardian,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3397044bdb66ad0a, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinDelaySeconds() uint64 {
	if m != nil {
		return m.MinDelaySeconds
	}
	return 0
}

func (m *Params) GetMaxDelaySeconds() uint64 {
	if m != nil {
		return m.MaxDelaySeconds
	}
	return 0
}

func (m *Params) GetGracePeriodSeconds() uint64 {
	if m != nil {
		return m.GracePeriodSeconds
	}
	return 0
}

func (m *Params) GetEmergencyDelaySeconds() uint64 {
	if m != nil {
		return m.EmergencyDelaySeconds
	}
	return 0
}

func (m *Params) GetGuardian() string {
	if m != nil {
		return m.Guardian
	}
	return ""
}

// QueuedOperation represents an operation waiting for execution
type QueuedOperation struct {
	// id is the unique identifier for this operation
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// proposal_id is the governance proposal that created this operation
	ProposalId uint64 `protobuf:"varint,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	// messages are the sdk.Msg objects to execute
	Messages []*any.Any `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	// operation_hash is the cryptographic hash of the operation for verification
	OperationHash []byte `protobuf:"bytes,4,opt,name=operation_hash,json=operationHash,proto3" json:"operation_hash,omitempty"`
	// queued_at_unix is when the operation was queued (Unix timestamp seconds)
	QueuedAtUnix int64 `protobuf:"varint,5,opt,name=queued_at_unix,json=queuedAtUnix,proto3" json:"queued_at_unix,omitempty"`
	// executable_at_unix is the earliest time the operation can be executed (Unix timestamp seconds)
	ExecutableAtUnix int64 `protobuf:"varint,6,opt,name=executable_at_unix,json=executableAtUnix,proto3" json:"executable_at_unix,omitempty"`
	// expires_at_unix is the latest time the operation can be executed (Unix timestamp seconds)
	ExpiresAtUnix int64 `protobuf:"varint,7,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	// status is the current state of the operation
	Status OperationStatus `protobuf:"varint,8,opt,name=status,proto3,enum=pos.timelock.v1.OperationStatus" json:"status,omitempty"`
	// executor is the address authorized to execute this operation
	Executor string `protobuf:"bytes,9,opt,name=executor,proto3" json:"executor,omitempty"`
	// executed_at_unix is when the operation was executed (Unix timestamp seconds, 0 if not executed)
	ExecutedAtUnix int64 `protobuf:"varint,10,opt,name=executed_at_unix,json=executedAtUnix,proto3" json:"executed_at_unix,omitempty"`
	// cancelled_at_unix is when the operation was cancelled (Unix timestamp seconds, 0 if not cancelled)
	CancelledAtUnix int64 `protobuf:"varint,11,opt,name=cancelled_at_unix,json=cancelledAtUnix,proto3" json:"cancelled_at_unix,omitempty"`
	// cancel_reason is the reason for cancellation (if applicable)
	CancelReason string `protobuf:"bytes,12,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	// execution_error is the error message if execution failed
	ExecutionError string `protobuf:"bytes,13,opt,name=execution_error,json=executionError,proto3" json:"execution_error,omitempty"`
}

func (m *QueuedOperation) Reset()         { *m = QueuedOperation{} }
func (m *QueuedOperation) String() string { return proto.CompactTextString(m) }
func (*QueuedOperation) ProtoMessage()    {}
func (*QueuedOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3397044bdb66ad0a, []int{1}
}
func (m *QueuedOperation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueuedOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueuedOperation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueuedOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuedOperation.Merge(m, src)
}
func (m *QueuedOperation) XXX_Size() int {
	return m.Size()
}
func (m *QueuedOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuedOperation.DiscardUnknown(m)
}

var xxx_messageInfo_QueuedOperation proto.InternalMessageInfo

func (m *QueuedOperation) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QueuedOperation) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *QueuedOperation) GetMessages() []*any.Any {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *QueuedOperation) GetOperationHash() []byte {
	if m != nil {
		return m.OperationHash
	}
	return nil
}

func (m *QueuedOperation) GetQueuedAtUnix() int64 {
	if m != nil {
		return m.QueuedAtUnix
	}
	return 0
}

func (m *QueuedOperation) GetExecutableAtUnix() int64 {
	if m != nil {
		return m.ExecutableAtUnix
	}
	return 0
}

func (m *QueuedOperation) GetExpiresAtUnix() int64 {
	if m != nil {
		return m.ExpiresAtUnix
	}
	return 0
}

func (m *QueuedOperation) GetStatus() OperationStatus {
	if m != nil {
		return m.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (m *QueuedOperation) GetExecutor() string {
	if m != nil {
		return m.Executor
	}
	return ""
}

func (m *QueuedOperation) GetExecutedAtUnix() int64 {
	if m != nil {
		return m.ExecutedAtUnix
	}
	return 0
}

func (m *QueuedOperation) GetCancelledAtUnix() int64 {
	if m != nil {
		return m.CancelledAtUnix
	}
	return 0
}

func (m *QueuedOperation) GetCancelReason() string {
	if m != nil {
		return m.CancelReason
	}
	return ""
}

func (m *QueuedOperation) GetExecutionError() string {
	if m != nil {
		return m.ExecutionError
	}
	return ""
}

// GenesisState defines the timelock module's genesis state
type GenesisState struct {
	// params are the module parameters
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// operations are all queued operations
	Operations []QueuedOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations"`
	// next_operation_id is the next available operation ID
	NextOperationId uint64 `protobuf:"varint,3,opt,name=next_operation_id,json=nextOperationId,proto3" json:"next_operation_id,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3397044bdb66ad0a, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetOperations() []QueuedOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *GenesisState) GetNextOperationId() uint64 {
	if m != nil {
		return m.NextOperationId
	}
	return 0
}

func init() {
	proto.RegisterEnum("pos.timelock.v1.OperationStatus", OperationStatus_name, OperationStatus_value)
	proto.RegisterType((*Params)(nil), "pos.timelock.v1.Params")
	proto.RegisterType((*QueuedOperation)(nil), "pos.timelock.v1.QueuedOperation")
	proto.RegisterType((*GenesisState)(nil), "pos.timelock.v1.GenesisState")
}

func init() { proto.RegisterFile("pos/timelock/v1/types.proto", fileDescriptor_3397044bdb66ad0a) }

var fileDescriptor_3397044bdb66ad0a = []byte{
	// 784 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xcb, 0x6e, 0xeb, 0x44,
	0x18, 0xc7, 0xe3, 0x24, 0x27, 0xb4, 0x93, 0x6b, 0x87, 0xa0, 0xba, 0x3d, 0x25, 0x8d, 0xca, 0x2d,
	0x8a, 0xc0, 0x39, 0xa7, 0x20, 0x84, 0xce, 0x2e, 0x17, 0x17, 0x22, 0x55, 0x6d, 0xea, 0x24, 0x12,
	0x62, 0x63, 0x4d, 0xed, 0xc1, 0x1d, 0x11, 0xcf, 0x98, 0x19, 0xa7, 0x72, 0x5e, 0x81, 0x15, 0x4f,
	0x80, 0x58, 0x22, 0xb1, 0xe9, 0x82, 0x35, 0xeb, 0x8a, 0x55, 0xc5, 0x8a, 0x15, 0x42, 0xed, 0xa2,
	0x3c, 0x06, 0x9a, 0xb1, 0xe3, 0xb6, 0x49, 0x25, 0x36, 0x51, 0xe6, 0xff, 0xff, 0x7d, 0xf9, 0x66,
	0xbe, 0x4b, 0xc0, 0xcb, 0x80, 0x89, 0x4e, 0x48, 0x7c, 0x3c, 0x63, 0xce, 0x77, 0x9d, 0xcb, 0xd7,
	0x9d, 0x70, 0x11, 0x60, 0x61, 0x04, 0x9c, 0x85, 0x0c, 0x56, 0x03, 0x26, 0x8c, 0xa5, 0x69, 0x5c,
	0xbe, 0xde, 0xdd, 0xf1, 0x18, 0xf3, 0x66, 0xb8, 0xa3, 0xec, 0xf3, 0xf9, 0xb7, 0x1d, 0x44, 0x17,
	0x31, 0xbb, 0xbb, 0xe3, 0x30, 0xe1, 0x33, 0x61, 0xab, 0x53, 0x27, 0x3e, 0x24, 0xd6, 0x16, 0xf2,
	0x09, 0x65, 0x1d, 0xf5, 0x99, 0x48, 0x75, 0x8f, 0x79, 0x2c, 0x46, 0xe5, 0xb7, 0x58, 0x3d, 0xf8,
	0x29, 0x0b, 0x0a, 0x23, 0xc4, 0x91, 0x2f, 0x60, 0x1b, 0x6c, 0xf9, 0x84, 0xda, 0x2e, 0x9e, 0xa1,
	0x85, 0x2d, 0xb0, 0xc3, 0xa8, 0x2b, 0x74, 0xad, 0xa9, 0xb5, 0xf2, 0x56, 0xd5, 0x27, 0x74, 0x20,
	0xf5, 0x71, 0x2c, 0x2b, 0x16, 0x45, 0x2b, 0x6c, 0x36, 0x61, 0x51, 0xf4, 0x84, 0x7d, 0x05, 0xea,
	0x1e, 0x47, 0x0e, 0xb6, 0x03, 0xcc, 0x09, 0x73, 0x53, 0x3c, 0xa7, 0x70, 0xa8, 0xbc, 0x91, 0xb2,
	0x96, 0x11, 0x9f, 0x83, 0x6d, 0xec, 0x63, 0xee, 0x61, 0xea, 0x2c, 0x56, 0x72, 0xe4, 0x55, 0xd0,
	0x3b, 0xa9, 0xfd, 0x24, 0xd3, 0x67, 0x60, 0xc3, 0x9b, 0x23, 0xee, 0x12, 0x44, 0xf5, 0x17, 0x4d,
	0xad, 0xb5, 0xd9, 0xd3, 0xff, 0xfc, 0xed, 0x93, 0x7a, 0x52, 0x99, 0xae, 0xeb, 0x72, 0x2c, 0xc4,
	0x38, 0xe4, 0x84, 0x7a, 0x56, 0x4a, 0xbe, 0xd9, 0xfb, 0xf7, 0xe7, 0x7d, 0xed, 0x87, 0xfb, 0xab,
	0xf6, 0xdb, 0x4f, 0x1a, 0x13, 0x57, 0xe5, 0xe0, 0xd7, 0x3c, 0xa8, 0x9e, 0xcd, 0xf1, 0x1c, 0xbb,
	0xa7, 0x01, 0xe6, 0x28, 0x24, 0x8c, 0xc2, 0x0a, 0xc8, 0x12, 0x37, 0x29, 0x4d, 0x96, 0xb8, 0x70,
	0x1f, 0x14, 0x03, 0xce, 0x02, 0x26, 0xd0, 0xcc, 0x26, 0x6e, 0x52, 0x07, 0xb0, 0x94, 0x86, 0x2e,
	0x7c, 0x05, 0x36, 0x7c, 0x2c, 0x04, 0xf2, 0xb0, 0x7c, 0x76, 0xae, 0x55, 0x3c, 0xac, 0x1b, 0x71,
	0x5f, 0x8d, 0x65, 0x5f, 0x8d, 0x2e, 0x5d, 0x58, 0x29, 0x05, 0x3f, 0x00, 0x15, 0xb6, 0xcc, 0x67,
	0x5f, 0x20, 0x71, 0xa1, 0x5e, 0x5e, 0xb2, 0xca, 0xa9, 0xfa, 0x15, 0x12, 0x17, 0xf0, 0x7d, 0x50,
	0xf9, 0x5e, 0x5d, 0xce, 0x46, 0xa1, 0x3d, 0xa7, 0x24, 0x52, 0xef, 0xce, 0x59, 0xa5, 0x58, 0xed,
	0x86, 0x53, 0x4a, 0x22, 0xf8, 0x31, 0x80, 0x38, 0xc2, 0xce, 0x3c, 0x44, 0xe7, 0x33, 0x9c, 0x92,
	0x05, 0x45, 0xd6, 0x1e, 0x9c, 0x84, 0xfe, 0x10, 0x54, 0x71, 0x14, 0x10, 0x8e, 0x45, 0x8a, 0xbe,
	0xa5, 0xd0, 0x72, 0x22, 0x27, 0xdc, 0x17, 0xa0, 0x20, 0x42, 0x14, 0xce, 0x85, 0xbe, 0xd1, 0xd4,
	0x5a, 0x95, 0xc3, 0xa6, 0xb1, 0x32, 0xbb, 0x46, 0x5a, 0xb1, 0xb1, 0xe2, 0xac, 0x84, 0x97, 0x7d,
	0x8a, 0xb3, 0x32, 0xae, 0x6f, 0xfe, 0x5f, 0x9f, 0x96, 0x24, 0x6c, 0x81, 0xe4, 0xae, 0x8f, 0x5e,
	0x0b, 0xd4, 0xc5, 0x2a, 0x4b, 0x3d, 0xb9, 0x59, 0x1b, 0x6c, 0x39, 0x88, 0x3a, 0x78, 0x36, 0x7b,
	0x84, 0x16, 0x15, 0x5a, 0x4d, 0x8d, 0x84, 0x7d, 0x0f, 0x94, 0x63, 0xc9, 0xe6, 0x18, 0x09, 0x46,
	0xf5, 0x92, 0xbc, 0x90, 0x55, 0x8a, 0x45, 0x4b, 0x69, 0xf0, 0x23, 0x59, 0x12, 0x99, 0x42, 0x76,
	0x03, 0x73, 0xce, 0xb8, 0x5e, 0x56, 0x58, 0x25, 0x95, 0x4d, 0xa9, 0x1e, 0xfc, 0xae, 0x81, 0xd2,
	0x97, 0x98, 0x62, 0x41, 0x84, 0x7c, 0x33, 0x86, 0x6f, 0x40, 0x21, 0x50, 0x83, 0xa4, 0xc6, 0xa5,
	0x78, 0xb8, 0xbd, 0x56, 0xa4, 0x78, 0xce, 0x7a, 0x9b, 0xd7, 0x7f, 0xef, 0x67, 0x7e, 0xb9, 0xbf,
	0x6a, 0x6b, 0x56, 0x12, 0x01, 0x8f, 0x00, 0x48, 0xbb, 0x2d, 0xb7, 0x4b, 0xce, 0xcd, 0x7a, 0x91,
	0x57, 0x86, 0xb3, 0x97, 0x97, 0x3f, 0x64, 0x3d, 0x8a, 0x94, 0xe5, 0xa0, 0x38, 0x0a, 0xed, 0x87,
	0x81, 0x22, 0x6e, 0xb2, 0x7d, 0x55, 0x69, 0xa4, 0xb1, 0x43, 0xb7, 0xfd, 0x87, 0x06, 0xaa, 0x2b,
	0x6d, 0x83, 0x4d, 0xb0, 0x77, 0x3a, 0x32, 0xad, 0xee, 0x64, 0x78, 0x7a, 0x62, 0x8f, 0x27, 0xdd,
	0xc9, 0x74, 0x6c, 0x4f, 0x4f, 0xc6, 0x23, 0xb3, 0x3f, 0x3c, 0x1a, 0x9a, 0x83, 0x5a, 0x06, 0xbe,
	0x04, 0xdb, 0x6b, 0xc4, 0xd9, 0xd4, 0x9c, 0x9a, 0x83, 0x9a, 0x06, 0xdf, 0x05, 0x3b, 0x6b, 0xa6,
	0xf9, 0xb5, 0xd9, 0x9f, 0x4e, 0xcc, 0x41, 0x2d, 0x0b, 0x1b, 0x60, 0x77, 0xcd, 0xee, 0x77, 0x4f,
	0xfa, 0xe6, 0xf1, 0xb1, 0x39, 0xa8, 0xe5, 0xe0, 0x1e, 0xd0, 0x9f, 0x09, 0x1f, 0x0d, 0x2d, 0x73,
	0x50, 0xcb, 0x3f, 0x9b, 0xf9, 0xa8, 0x3b, 0x94, 0xa1, 0x2f, 0x7a, 0xc6, 0xf5, 0x6d, 0x43, 0xbb,
	0xb9, 0x6d, 0x68, 0xff, 0xdc, 0x36, 0xb4, 0x1f, 0xef, 0x1a, 0x99, 0x9b, 0xbb, 0x46, 0xe6, 0xaf,
	0xbb, 0x46, 0xe6, 0x9b, 0xba, 0x5c, 0xf5, 0xe8, 0x61, 0xd9, 0xd5, 0x5f, 0xf0, 0x79, 0x41, 0x2d,
	0xe3, 0xa7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xce, 0xb6, 0xe9, 0xa2, 0x05, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MinDelaySeconds != that1.MinDelaySeconds {
		return false
	}
	if this.MaxDelaySeconds != that1.MaxDelaySeconds {
		return false
	}
	if this.GracePeriodSeconds != that1.GracePeriodSeconds {
		return false
	}
	if this.EmergencyDelaySeconds != that1.EmergencyDelaySeconds {
		return false
	}
	if this.Guardian != that1.Guardian {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Guardian) > 0 {
		i -= len(m.Guardian)
		copy(dAtA[i:], m.Guardian)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Guardian)))
		i--
		dAtA[i] = 0x2a
	}
	if m.EmergencyDelaySeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.EmergencyDelaySeconds))
		i--
		dAtA[i] = 0x20
	}
	if m.GracePeriodSeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.GracePeriodSeconds))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxDelaySeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MaxDelaySeconds))
		i--
		dAtA[i] = 0x10
	}
	if m.MinDelaySeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.MinDelaySeconds))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueuedOperation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueuedOperation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueuedOperation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExecutionError) > 0 {
		i -= len(m.ExecutionError)
		copy(dAtA[i:], m.ExecutionError)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ExecutionError)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.CancelReason) > 0 {
		i -= len(m.CancelReason)
		copy(dAtA[i:], m.CancelReason)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CancelReason)))
		i--
		dAtA[i] = 0x62
	}
	if m.CancelledAtUnix != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CancelledAtUnix))
		i--
		dAtA[i] = 0x58
	}
	if m.ExecutedAtUnix != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExecutedAtUnix))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Executor) > 0 {
		i -= len(m.Executor)
		copy(dAtA[i:], m.Executor)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Executor)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Status != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	if m.ExpiresAtUnix != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExpiresAtUnix))
		i--
		dAtA[i] = 0x38
	}
	if m.ExecutableAtUnix != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ExecutableAtUnix))
		i--
		dAtA[i] = 0x30
	}
	if m.QueuedAtUnix != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.QueuedAtUnix))
		i--
		dAtA[i] = 0x28
	}
	if len(m.OperationHash) > 0 {
		i -= len(m.OperationHash)
		copy(dAtA[i:], m.OperationHash)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.OperationHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Messages) > 0 {
		for iNdEx := len(m.Messages) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Messages[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ProposalId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ProposalId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextOperationId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.NextOperationId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Operations) > 0 {
		for iNdEx := len(m.Operations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Operations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinDelaySeconds != 0 {
		n += 1 + sovTypes(uint64(m.MinDelaySeconds))
	}
	if m.MaxDelaySeconds != 0 {
		n += 1 + sovTypes(uint64(m.MaxDelaySeconds))
	}
	if m.GracePeriodSeconds != 0 {
		n += 1 + sovTypes(uint64(m.GracePeriodSeconds))
	}
	if m.EmergencyDelaySeconds != 0 {
		n += 1 + sovTypes(uint64(m.EmergencyDelaySeconds))
	}
	l = len(m.Guardian)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *QueuedOperation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	if m.ProposalId != 0 {
		n += 1 + sovTypes(uint64(m.ProposalId))
	}
	if len(m.Messages) > 0 {
		for _, e := range m.Messages {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = len(m.OperationHash)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.QueuedAtUnix != 0 {
		n += 1 + sovTypes(uint64(m.QueuedAtUnix))
	}
	if m.ExecutableAtUnix != 0 {
		n += 1 + sovTypes(uint64(m.ExecutableAtUnix))
	}
	if m.ExpiresAtUnix != 0 {
		n += 1 + sovTypes(uint64(m.ExpiresAtUnix))
	}
	if m.Status != 0 {
		n += 1 + sovTypes(uint64(m.Status))
	}
	l = len(m.Executor)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.ExecutedAtUnix != 0 {
		n += 1 + sovTypes(uint64(m.ExecutedAtUnix))
	}
	if m.CancelledAtUnix != 0 {
		n += 1 + sovTypes(uint64(m.CancelledAtUnix))
	}
	l = len(m.CancelReason)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.ExecutionError)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.Operations) > 0 {
		for _, e := range m.Operations {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.NextOperationId != 0 {
		n += 1 + sovTypes(uint64(m.NextOperationId))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDelaySeconds", wireType)
			}
			m.MinDelaySeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDelaySeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDelaySeconds", wireType)
			}
			m.MaxDelaySeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDelaySeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GracePeriodSeconds", wireType)
			}
			m.GracePeriodSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GracePeriodSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EmergencyDelaySeconds", wireType)
			}
			m.EmergencyDelaySeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EmergencyDelaySeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Guardian", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Guardian = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueuedOperation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueuedOperation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueuedOperation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			m.ProposalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProposalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Messages", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Messages = append(m.Messages, &any.Any{})
			if err := m.Messages[len(m.Messages)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperationHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperationHash = append(m.OperationHash[:0], dAtA[iNdEx:postIndex]...)
			if m.OperationHash == nil {
				m.OperationHash = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueuedAtUnix", wireType)
			}
			m.QueuedAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QueuedAtUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutableAtUnix", wireType)
			}
			m.ExecutableAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutableAtUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAtUnix", wireType)
			}
			m.ExpiresAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAtUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= OperationStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Executor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutedAtUnix", wireType)
			}
			m.ExecutedAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutedAtUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CancelledAtUnix", wireType)
			}
			m.CancelledAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CancelledAtUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CancelReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CancelReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutionError", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExecutionError = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operations = append(m.Operations, QueuedOperation{})
			if err := m.Operations[len(m.Operations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextOperationId", wireType)
			}
			m.NextOperationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextOperationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
